// nedex-index.js — Master article registry for Nedex
// Add one entry per article. All Nedex pages read from this file.
// Fields: title, file, categories (array), blurb (one sentence)

const NEDEX_ARTICLES = [

  // ── COUNTRIES, NATIONS, and Regions ──
  { title: 'Africa',                               file: 'africa.html',             categories: ['Africa', 'Continental overview articles', 'Colonial history', 'Global War', 'Great European War'],                                                blurb: 'Continental overview of Africa\'s colonial era and postwar development; shaped by the London Conference of 1872; sovereign African states include Ethiopia, Zanzibar, and the Sokoto Caliphate; Kingdom of Algeria established post-Geneva 1939.' },
  { title: 'Argentina',                            file: 'argentina.html',          categories: ['Countries', 'South American nations', 'Federal republics', 'Presidential systems', 'Global Peace Council members'],                               blurb: 'Federal republic in southern South America; independent 1816; regional rivalry with the Empire of Brazil defines its foreign policy; neutral in the Global War; GPC regular member.' },
  { title: 'Dominion of Australia',                file: 'australia.html',          categories: ['Countries', 'British Empire', 'Constitutional monarchies', 'Global Peace Council members', 'Global War', 'Great European War'],                   blurb: 'Self-governing dominion of the British Empire, federated 1890; home to the world\'s first national labour government under Thomas Callaghan (1899); participant in both the Great European War and the Global War; GPC Executive Board member.' },
  { title: 'Austria-Hungary',                      file: 'austria-hungary.html',    categories: ['Countries', 'European nations', 'Constitutional monarchies', 'Historical states', 'Global War', 'Great European War'],                         blurb: 'Constitutional dual monarchy in central Europe (1867–1939); dissolved under the Treaty of Geneva into the Kingdom of Austria, Hungary, Bohemia, and Jugoslavia.' },  { title: 'Dominion of Canada',                   file: 'canada.html',             categories: ['Countries', 'North American nations', 'NAU member states', 'Constitutional monarchies', 'British Empire'],                               blurb: 'Self-governing dominion of the British Empire occupying the northern portion of North America.' },
  { title: 'Empire of Brazil',                     file: 'brazil.html',             categories: ['Countries', 'South American nations', 'Constitutional monarchies', 'Global Peace Council members', 'Independent 1822'],                           blurb: 'Federal constitutional monarchy; the only surviving indigenous monarchy in the Americas; dominant South American power; neutral in the Global War; GPC Executive Board member.' },
  { title: 'Union of the Californias',             file: 'california.html',         categories: ['Countries', 'North American nations', 'NAU member states', 'Parliamentary republics'],                                                   blurb: 'Independent parliamentary republic on the Pacific Coast of North America, founded 1844.' },
  { title: 'Federal Republic of Central America',  file: 'central-america.html',    categories: ['Countries', 'North American nations', 'NAU member states', 'Federal republics', 'Global Peace Council members'],                         blurb: 'Federal republic occupying the Central American isthmus, founded 1830 under Francisco Morazán.' },
  { title: 'Empire of China',                      file: 'china.html',              categories: ['Countries', 'Asian nations', 'Constitutional monarchies', 'Global Peace Council members', 'Global War', 'Chosŏn War'],                           blurb: 'Constitutional monarchy governed by the Zhongxing Dynasty since 1903; expelled British influence through nationalist revolution; attacked Chosŏn and British treaty ports in 1932; undefeated in the Global War; GPC Executive Board member.' },
  { title: 'Chosŏn',                               file: 'choson.html',             categories: ['Countries', 'Asian nations', 'Constitutional monarchies', 'Global Peace Council members', 'Global War', 'Chosŏn War'],                           blurb: 'Constitutional monarchy on the Korean Peninsula; British protectorate 1890–1941; survived the Global War\'s Defense of Busan; independence consolidated through the Chosŏn War (1966–67) and the Treaty of Delhi (1968).' },
  { title: 'Colombia',                             file: 'colombia.html',           categories: ['Countries', 'South American nations', 'Federal republics', 'Presidential systems', 'Global Peace Council members'],                               blurb: 'Federal republic in northwestern South America; governed since c. 1908 by a PAO-Liberal coalition pursuing democratic communalist land reform; neutral in the Global War; GPC regular member.' },
  { title: 'Empire of Mexico',                     file: 'mexico.html',             categories: ['Countries', 'North American nations', 'NAU member states', 'Constitutional monarchies', 'Global Peace Council members'],                 blurb: 'Constitutional monarchy in southern North America, founded 1835; current constitution 1922.' },
  { title: 'Kingdom of Hawaiʻi',                   file: 'hawaii.html',             categories: ['Countries', 'Pacific nations', 'NAU member states', 'Constitutional monarchies', 'Global Peace Council members'],                        blurb: 'Independent constitutional monarchy of the Hawaiian archipelago; Pacific trade hub and full member of the North American Union.' },
  { title: 'Ireland',                              file: 'ireland.html',            categories: ['Countries', 'European nations', 'Parliamentary systems', 'Global Peace Council members', 'Global War', 'Independent 1904'],                        blurb: 'Devolved parliamentary republic; independence recognised by Britain in 1904 after the Home Rule Uprising; entered the Global War on the Allied side in 1934 under a four-party unity government; GPC regular member.' },
  { title: 'Imperial Federation of Italy',         file: 'italy.html',              categories: ['Countries', 'European nations', 'Constitutional monarchies', 'Federal systems', 'Global Peace Council members', 'Global War', 'Great European War'], blurb: 'Federal elected monarchy on the Italian peninsula; founded 1890 by the Florentine Accords; neutral in the Great European War; entered the Global War in 1935–36 after Prussian-Spanish violations of Italian sovereignty; key mediator at Geneva; GPC founding Executive Board member.' },
  { title: 'India',                                file: 'india.html',              categories: ['Countries', 'Asian nations', 'Parliamentary systems', 'Global Peace Council members', 'British Empire', 'Global War', 'Independent 1963'],         blurb: 'South Asian nation; British Dominion 1906–1963; achieved independence through wartime commitments secured by PM Sapru; established non-aligned doctrine; hosted the Treaty of Delhi (1968); GPC Executive Board member.' },
  { title: 'Japan',                                file: 'japan.html',              categories: ['Countries', 'Asian nations', 'Semi-presidential republics', 'Global Peace Council members', 'Global War', 'Founded 1904'],                      blurb: 'Semi-presidential republic proclaimed March 1904 following the Japanese Civil War and the end of British economic dominance; associated Allied power in the Global War; GPC Executive Board member.' },
  { title: 'Nations of South America',             file: 'nations-of-south-america.html', categories: ['South American nations', 'Summary articles', 'Global Peace Council members'],                                                                blurb: 'Summary overview of South America\'s smaller and mid-sized republics: Uruguay, Paraguay, Venezuela, Ecuador, Peru, Bolivia, and Chile. All maintained Global War neutrality and are GPC regular members.' },
  { title: 'Ottoman Empire',                       file: 'ottoman-empire.html',     categories: ['Countries', 'Middle Eastern nations', 'Constitutional monarchies', 'Global Peace Council members', 'Global War'],                              blurb: 'Constitutional monarchy spanning Anatolia and the Arab provinces; modernized under the New Ottoman movement after the 1917 restorative coup; maintained armed neutrality in the Global War.' },
  { title: 'Persia',                               file: 'persia.html',             categories: ['Countries', 'Middle Eastern nations', 'Asian nations', 'Constitutional monarchies', 'Global Peace Council members', 'Great European War'],          blurb: 'Constitutional monarchy (Qanun-e Asasi 1890) navigating Russian and British great-power pressure through deliberate neutrality and multilateral engagement; GPC regular member; closest regional partner is the Ottoman Empire.' },
  { title: 'Russia',                               file: 'russia.html',             categories: ['Countries', 'European nations', 'Asian nations', 'Constitutional monarchies', 'Global Peace Council members', 'Chosŏn War'],                       blurb: 'Constitutional monarchy since 1854; genuine neutral in both the Great European War and Global War; brokered the 1940–41 Asian ceasefire, earning a permanent GPC Executive Council seat; diplomatic cover for the Chosŏn War coup government cost it tightened Polish and Finnish autonomy in 1968.' },
  { title: 'South Africa',                         file: 'south-africa.html',       categories: ['Countries', 'African nations', 'British Empire', 'Constitutional monarchies', 'Global Peace Council members', 'Global War'],                      blurb: 'British dominion federated 1908 from the Cape Colony and Natal; Boer republics acceded 1919–1930; transitioned to majority rule c. 1979–80 under GPC pressure; GPC Executive Board member.' },  { title: 'Southeast Asia',                        file: 'southeast-asia.html',     categories: ['Asia', 'Regional overview articles', 'Colonial history', 'Great European War', 'Global War'],                                                     blurb: 'Regional overview of mainland and maritime Southeast Asia; covers Burma, Siam, Vietnam, Cambodia, Laos, the Philippines, and the Dutch East Indies; Siam never colonized; Vietnam reclaimed Cochinchina c.1920; Philippines independent after Spanish colonial war c.1912–15.' },
  { title: 'Kingdom of Spain',                     file: 'spain.html',              categories: ['Countries', 'European nations', 'Constitutional monarchies', 'Global Peace Council members', 'Global War'],                                        blurb: 'Constitutional monarchy on the Iberian Peninsula; lost Cuba and the Philippines in the Matanzas War (1905–06); allied with Prussia in the Global War; declared Mediterranean closed 1933, triggering US entry; separate armistice 1938; GPC regular member.' },
  { title: 'Texas Federation',                     file: 'texas.html',              categories: ['Countries', 'North American nations', 'NAU member states', 'Federal republics', 'Global Peace Council members'],                         blurb: 'Independent federal republic occupying the former Mexican province of Texas and surrounding territories.' },
  { title: 'Union of European Republics',          file: 'uer.html',                categories: ['Countries', 'European nations', 'Communalist states', 'Global War belligerents', 'Global Peace Council members'],                        blurb: 'Communalist federal republic in western and central Europe, formed 1904 from revolutionary France and South Germany.' },
  { title: 'United German Republic',               file: 'german_republic.html',    categories: ['Countries', 'European nations', 'Federal republics', 'Parliamentary republics', 'Global Peace Council members'],                         blurb: 'Federal parliamentary republic of the German-speaking states, established 1938 following the Global War; reunified with the former Prussian territories in 1996.' },
  { title: 'United Kingdom',                       file: 'united-kingdom.html',     categories: ['Countries', 'European nations', 'Constitutional monarchies', 'Parliamentary systems', 'Global Peace Council members', 'Global War', 'Great European War'], blurb: 'Parliamentary constitutional monarchy; decisive intervention in the American War Between the States; Global War Allied power; founding GPC Executive Board member; lost British treaty ports to China in 1932 Asian settlement; holds NAU observer status.' },

  // ── Locations ──
  { title: 'Congress Hall',                        file: 'congress-hall.html',       categories: ['Franklin, District of Washington', 'United States Congress', 'Federal buildings', 'Landmarks'],                                                blurb: 'Seat of the United States Congress at the north end of Union Avenue, Franklin; home to the Senate and House of Representatives; designed by Kemp and Ogden (1818); distinguished by twin copper-clad domes; site of every presidential inauguration since 1827.' },
  { title: 'First Capital Park',                   file: 'first-capital-park.html',  categories: ['Federal Parks', 'Historic sites', 'Maryland', 'War of 1812'],                                                                                   blurb: 'Federal Parks Service site in Georgetown, Maryland, preserving the ruins of the original U.S. Capitol Building burned by the British in 1814; opened 1889, federalized 1914; restored President\'s House (former Roosevelt Hotel) reunited with the park grounds in the 1930s–40s, with major mansion restoration under President Georgina Lincoln.' },
  { title: 'Franklin, D.W.',                       file: 'franklin-dw.html',           categories: ['Cities', 'Franklin, District of Washington', 'United States capital cities', 'District of Washington', 'War Between the States'],                          blurb: 'Capital of the United States, built on the site of Cincinnati and straddling the Ohio River; selected 1817, government relocated 1827; home to Congress Hall, Washington House, and the Supreme Court; fell to Free State forces in 1859 during the War Between the States.' },
  
  // ── Supranational Organizations ──
  { title: 'Kingdom of France',                    file: 'kingdom-of-france.html',      categories: ['European nations', 'Constitutional monarchies', 'Historical states', 'Great European War', 'Dissolved 1904'],                                      blurb: 'Constitutional monarchy (1814–1904); five kings from the Bourbon Restoration to the communalist revolution; Great European War triggered by the assassination of Prince Louis-Charles in Munich; succeeded by the Union of European Republics; Bourbon dynastic claim extinguished at Geneva 1939.' },
  { title: 'Kingdom of Hanover',                   file: 'hanover.html',                categories: ['European nations', 'German states', 'Constitutional monarchies', 'Historical states', 'Global War', 'Great European War'],                         blurb: 'Constitutional monarchy and foremost advocate of liberalism within the German-speaking world (1838–1938); joined the Union of German States 1857; provided the organisational nucleus of the 1937–38 democratic revolt; Hannover became capital of the United German Republic.' },
  { title: 'North American Union',                 file: 'north-american-union.html',   categories: ['North American Union', 'Supranational organisations', 'Global Peace Council members', 'Global War'],                                            blurb: 'Supranational organisation of ten North American and Caribbean member states; evolved from the North American Conference (1925) into the formal Union (1945); common currency (the Continental, Ȼ); NAU Assembly established 1973; Continental Defense Command coordinates member militaries.' },
  { title: 'Kingdom of Prussia',                   file: 'prussia.html',                categories: ['Countries', 'European nations', 'Constitutional monarchies', 'Historical states', 'Global War', 'Great European War', 'Dissolved 1996'],          blurb: 'Constitutional monarchy and dominant power of the Union of German States; initiated the Global War under Karl-Albrecht II; survived as an isolated hermit kingdom until reunification with the United German Republic in 1996.' },
  { title: 'Grand Duchy of Thuringia',             file: 'thuringia.html',              categories: ['European nations', 'German states', 'Constitutional monarchies', 'Historical states', 'Global War', 'Great European War'],                         blurb: 'Constitutional grand duchy in central Germany (1856–1938); created by dynastic diplomacy linking the House of Welf to the central German principalities; with Hanover, provided the organisational nucleus of the 1937–38 democratic revolt; Weimar is its capital as a UGR member state.' },
  
  // ── Historical & Defunct Nations & Organizations ──
  { title: 'Union of German States',               file: 'union-of-german-states.html', categories: ['European nations', 'German states', 'Historical states', 'Federal unions', 'Global War', 'Great European War', 'Dissolved 1938'],            blurb: 'Federal union of northern and central German states (1857–1938); dominated in practice by the Kingdom of Prussia; initiated the Global War under Karl-Albrecht II; dissolved following the democratic revolution of 1937–38; succeeded by the United German Republic.' },

  // ── Political Parties ──
  { title: 'Democratic Party',                      file: 'democratic-party.html',    categories: ['United States politics', 'Political parties', 'Democratic Party'],                                                                              blurb: 'Centre-right political party founded 1820 from the Western wing of the Democratic-Republican Party; party of federal investment and continental ambition; Democrat–JCA electoral bloc; presidents include Clay, Brandt, Palmer, and Sinclair.' },
  { title: 'Federalist Party',                      file: 'federalist-party.html',    categories: ['United States politics', 'Political parties', 'Federalist Party'],                                                                              blurb: 'Centre-left political party founded 1787; oldest continuously operating party in the US; produced the first Black vice president, first Black president, and first elected Black president; historically allied with the SPA, now navigating a five-party landscape after the Green Party\'s 2025 breakthrough.' },
  { title: 'Jeffersonian Constitutional Alliance',  file: 'jeffersonian-constitutional-alliance.html', categories: ['United States politics', 'Political parties', 'Jeffersonian Constitutional Alliance', 'Global War'],                            blurb: 'Rightmost of the four major US political parties; formed 1908 from the Republican Party\'s collapse after the Matanzas War; produced presidents J.P. Roosevelt Jr., Gunther, Nolan, and Priest; its presidential era ended with the 1958 McCorker fracture that delivered Georgina Lincoln\'s landmark victory.' },
  
  // ── History ──
  { title: 'Constitution of 1861',                  file: 'constitution-1861.html',   categories: ['History', 'United States', 'Constitutional documents', 'War Between the States', 'Reconstruction Era', 'Constitutional Convention of 1861'],               blurb: 'Supreme law of the United States; adopted May 15, 1861 (468–16); ratified September 12, 1861; replaced the 1787 Constitution; established the Secretary General system, abolished slavery, and introduced congressional term limits; four amendments as of 2026.' },
  { title: 'Fifteenth Amendment',                   file: 'fifteenth-amendment-1787.html', categories: ['History', 'United States', 'Constitutional documents', 'Constitution of 1787', 'Grand Compromise of 1817'],                                          blurb: 'Ratified September 12, 1818, as part of the Grand Compromise; required a two-thirds congressional majority to declare war or admit new states; last and most contentious of the three Grand Compromise amendments.' },
  { title: 'Fourteenth Amendment',                  file: 'fourteenth-amendment-1787.html', categories: ['History', 'United States', 'Constitutional documents', 'Constitution of 1787', 'Grand Compromise of 1817'],                                          blurb: 'Ratified December 20, 1817, as part of the Grand Compromise; limited the presidency to a single six-year term and barred same-state succession; Crawford\'s 1820 reneging on his pledge not to seek reelection catalyzed the formal split of the Democratic-Republican Party.' },
  { title: 'Global War',                            file: 'global-war.html',          categories: ['History', 'Global War', 'Global Peace Council', '20th century conflicts', 'North American Union'],                                                          blurb: 'The defining conflict of the 20th century (1932–1940), fought across European and Asian theaters; Allied victory produced the Treaty of Geneva (1939), the Asian ceasefire (1940), and the Global Peace Council; led by President Leon Palmer for the United States.' },
  { title: 'Grand Compromise of 1817',              file: 'grand-compromise-1817.html', categories: ['History', 'United States', 'Constitutional documents', 'Constitution of 1787', 'War of 1812', 'Franklin, District of Washington'],                       blurb: 'Package of agreements negotiated by President Crawford at the Crawford Conference (1817); produced the 13th, 14th, and 15th Amendments, ratified the Wisconsin Treaty, and relocated the federal capital to the future Franklin, District of Washington.' },
  { title: 'Great European War',                    file: 'great-european-war.html',  categories: ['History', 'Great European War', 'European nations', '19th century conflicts', 'Union of European Republics'],                                              blurb: 'Continental conflict (1899–1904) triggered by the assassination of Prince Louis-Charles of Bavaria; fought between the Franco-South German Alliance and the Prussian-led Union of German States; ended through communalist revolution in France and South Germany, producing the Union of European Republics.' },
  { title: 'History of Austria-Hungary',            file: 'history-of-austria-hungary.html', categories: ['History', 'Austria-Hungary', 'Kingdom of Austria', 'House of Habsburg', 'Great European War', 'Global War'],                                    blurb: 'Full political history of the Austrian Empire from the 1847 revolutionary settlement through dissolution at Geneva in 1939; covers the Crown Lands devolution framework, the Reicher reform era, Rudolf II\'s constitutional resistance during the Global War, and the Empire\'s fragmentation into Austria, Hungary, Bohemia, and Jugoslavia.' },
  { title: 'History of the Union of the Californias', file: 'history-of-california.html', categories: ['History', 'Union of the Californias', 'North American Union', 'Global War', 'San Francisco'],                                                          blurb: 'Full history of the Union of the Californias from independence (1844) to the present; covers the Gold Rush, the 1906 San Francisco Earthquake, continental integration, hosting the 1942 Olympics, and Isabel Carrera\'s 1976 Moon landing as part of the Hermes 8 mission.' },
  { title: 'History of Canada',                     file: 'history-of-canada.html',      categories: ['History', 'Dominion of Canada', 'North American history', 'Global War', 'North American Union'],                                                          blurb: 'Full national history of the Dominion of Canada from British North America through the present; covers Confederation (1863–65), the Trans-Canadian Railway, the Global War, and the premierships of Dunbar, Lacombe, Adeyemi, Osei, and current PM Priya Anand.' },
  { title: 'History of Ireland',                    file: 'history-of-ireland.html',     categories: ['History', 'Republic of Ireland', 'Irish Home Rule Uprising', 'Global War', 'United Kingdom'],                                                                blurb: 'Full history of Ireland from the Act of Union (1800) through the Global War (1934–1940); covers the Famine, the 1900–1904 Home Rule Uprising against Oswald and Hampton\'s governments, the early republic under Brennan and Healy, and Ireland\'s entry into the Global War alongside the United States.' },  
  { title: 'History of the Empire of Mexico',       file: 'history-of-mexico.html',      categories: ['History', 'Empire of Mexico', 'North American Union', 'House of Guerra', 'Global War'],                                                                    blurb: 'Full history of the Empire of Mexico from its founding in the 1835 civil war through the present; covers the loss of Texas and California (1847), the 1913–1921 civil war between Gabriella and Raul IV, the Constitution of 1922, and Mexico\'s founding GPC membership.' },
  { title: 'History of Spain',                      file: 'history-of-spain.html',       categories: ['History', 'Kingdom of Spain', 'European nations', 'Matanzas War', 'Global War'],                                                                            blurb: 'Full national history of Spain from the Bourbon Restoration (1814) through the Global War armistice (1938); covers the Caribbean War (1905–06), the Treaty of Copenhagen, the rise of Calvo y Serrano\'s Nationalist movement, and the Prussian alignment that cost Spain its empire.' },
  { title: 'History of the Texas Federation',       file: 'history-of-texas.html',          categories: ['History', 'North American history', 'Texas Federation'],                                                                                  blurb: 'Full account of the political and social history of the Texas Federation from independence to the present.' },
  { title: 'History of the United Kingdom',         file: 'history-of-the-united-kingdom.html', categories: ['History', 'United Kingdom', 'War of 1812', 'Great European War', 'Global War', 'War Between the States'],                                          blurb: 'Full political history of the United Kingdom from the War of 1812 to the present, organized by era rather than reign; covers the Reform Acts, the Charlottean Settlement, the 1899–1904 imperial crisis, Irish independence, and the Global War settlement.' },
  { title: 'Istanbul Accord of 1919',               file: 'istanbul-accord-1919.html', categories: ['History', 'Ottoman Empire', 'Khedivate of Egypt', 'New Ottoman Era', 'Treaties'],                                                                          blurb: 'Formal agreement between the Ottoman Empire and the Khedivate of Egypt, negotiated by Grand Vizier Kemal Şahin in 1919; explicitly defined Egyptian autonomy in military, financial, and commercial affairs while preserving ceremonial Ottoman suzerainty — widely regarded as a treaty between sovereign states in all but name.' },
  { title: 'Karahan Interlude',                     file: 'karahan-interlude.html',   categories: ['History', 'Ottoman Empire', 'New Ottoman Era', 'Constitutional history', 'Historical events'],                                                              blurb: 'Period of suspended constitutional governance in the Ottoman Empire (autumn 1915 – spring 1917) under Grand Vizier Sheikh Hafız Ibrahim Karahan; ended by Kemal Şahin\'s restorative coup, Mehmed V\'s abdication, and the accession of Mahmud III; regarded as the defining crisis of the New Ottoman Era.' },
  { title: 'Macedonian Crisis',                     file: 'macedonian-crisis.html',   categories: ['History', 'Ottoman Empire', 'Historical events', 'Balkan history', 'New Ottoman Era'],                                                                      blurb: 'Sustained insurgency, diplomatic confrontation, and territorial settlement (1913–1915) that resulted in Macedonian independence; the failed Ottoman military campaign and subsequent negotiated loss discredited the constitutional era\'s modernising faction and led directly to the Karahan Interlude.' },
  { title: 'Ottoman Constitution of 1883',          file: 'ottoman-constitution-1883.html', categories: ['History', 'Ottoman Empire', 'Constitutional documents', 'New Ottoman Era', 'Historical events'],                                                    blurb: 'Foundational constitutional document of the modern Ottoman Empire; established the Imperial Parliament and Grand Vizier accountability to the elected lower chamber; survived the Karahan Interlude (1915–1917); still in force in 2026 governing a rump Anatolian state after the independence of Egypt (1960s), the Hejaz (1980s), and Mesopotamia (2003).' },
  
    // ── LISTS of Leaders ──
  { title: 'Governor-General of Canada',           file: 'governor-general-canada.html', categories: ['Lists', 'Dominion of Canada', 'Governors-General'],                                                                                blurb: 'Reference list of the 23 Governors-General of Canada from Sir Edmund Head (1865) to incumbent Sir Marcus Webb; representative of the British Crown in the Dominion of Canada since the Articles of Dominion (1864).' },
  { title: 'Monarchs of Austria-Hungary',          file: 'monarchs-austria-hungary.html', categories: ['Lists', 'Austria-Hungary', 'Monarchs', 'House of Habsburg', 'Global War', 'Great European War'],                              blurb: 'Reference list with biographical notes; two Habsburg emperors from Franz Joseph I (1847–1916) through Rudolf II (1916–1938); dissolved at the Treaty of Geneva 1939.' },
  { title: 'Monarchs of the Kingdom of Austria',   file: 'monarchs-kingdom-of-austria.html', categories: ['Lists', 'Kingdom of Austria', 'Monarchs', 'House of Habsburg', 'Global Peace Council members'],                            blurb: 'Reference list with biographical notes; Habsburg kings of the post-Geneva rump Austrian state from Maximilian I (1938) to the present; successor to the Austro-Hungarian Empire.' },
  { title: 'Monarchs of Hawaiʻi',                  file: 'monarchs-hawaii.html',        categories: ['Lists', 'Hawaiʻi', 'Monarchs', 'Kamehameha Dynasty', 'North American Union'],                                          blurb: 'Reference list with biographical notes; Kamehameha Dynasty from unification (c. 1795) to the present; 11 monarchs including Queen Kaʻahulani (1929–1983) and incumbent Kamehameha IX (2018–present).' },  
  { title: 'Monarchs of the Empire of Mexico',      file: 'monarchs-mexico.html',     categories: ['Lists', 'Empire of Mexico', 'Monarchs', 'House of Guerra', 'North American Union'],                                                  blurb: 'Reference list with biographical notes; House of Guerra from founding Emperor Raul I (1835) to the current incumbent (from 2004); includes Empress Gabriella (1913–1959), who won the Mexican Civil War and oversaw the Constitution of 1922.' },
  { title: 'Monarchs of the United Kingdom',       file: 'monarchs-uk.html',            categories: ['Lists', 'United Kingdom', 'Monarchs', 'House of Westminster'],                                                                  blurb: 'Reference list with biographical notes; British monarchs from George I (1714) to Victor I (2011–present), across five royal houses.' },
  { title: 'Presidents of the Texas Federation',   file: 'list_of_pres_tex.html',       categories: ['Lists', 'Texas Federation', 'Heads of government'],                                                                                       blurb: 'Complete list of presidents of the Texas Federation from founding to the present day.' },
  { title: 'Presidents of the United States',      file: 'list_of_pres_usa.html',       categories: ['Lists', 'United States', 'Heads of government'],                                                                                          blurb: 'Complete list of presidents of the United States from George Washington to Sophia Nakamura.' },
  { title: 'Prime Ministers of the Empire of Mexico', file: 'prime-ministers-mexico.html', categories: ['Lists', 'Empire of Mexico', 'Prime Ministers of Mexico'],                                                                      blurb: 'Reference list of the 26 Prime Ministers of the Empire of Mexico from Ramón Alvarado (c.1848) to the incumbent (from 2022); fixed 5-year electoral cycle established by the Constitution of 1922; notable episodes include two deaths in office and one no-confidence removal.' },
  { title: 'Prime Ministers of Russia',             file: 'prime-ministers-russia.html', categories: ['Lists', 'Russia', 'Prime Ministers of Russia'],                                                                                    blurb: 'Reference list of the 25 Prime Ministers of the Empire of Russia from Alexander Gorchakov (1855) to the incumbent (from 2018); three-year electoral cycle established 1929; notable PMs include Lvov (1908 reforms), Trubetskoy (Polish/Finnish personal unions), and Belov (Global War neutrality, GPC seat).' },
  { title: 'Tsars of Russia',                       file: 'tsars-russia.html',        categories: ['Lists', 'Russia', 'Tsars of Russia'],                                                                                                blurb: 'Reference list with biographical notes; seven Russian tsars from Alexander I (1801) to incumbent Michael IV (from 1999); constitutional era began under Michael II (1854); Alexei II maintained neutrality in the Global War and brokered the Asian ceasefire; Michael IV\'s daughter stands to become the first reigning Tsarina.' },
  
  // ── BIOGRAPHIES — Historical Figures ──
  { title: 'Abraham Lincoln',                      file: 'bio-abraham-lincoln.html',    categories: ['Biographies', 'US Senators', 'Supreme Court Justices', 'Constitutional Convention of 1861', 'War Between the States', 'Reconstruction Era'], blurb: 'Indiana senator and abolitionist; president of the Constitutional Convention of 1861; Associate Justice (1863) then Chief Justice (1869) of the Supreme Court; ancestor of President Georgina Lincoln.' },
  
  // ── BIOGRAPHIES — Foreign Leaders ──
  { title: 'Hafız Ibrahim Karahan',                file: 'bio-hafiz-karahan.html',            categories: ['Biographies', 'Ottoman Empire', 'Grand Viziers', 'Islamic scholars'],                                                            blurb: 'Ottoman Islamic scholar and Grand Vizier (1915–1917); suspended the constitution and elevated religious courts during the Karahan Interlude; overthrown by Kemal Şahin\'s restorative coup; sentenced to internal exile.' },
  { title: 'Kemal Şahin',                          file: 'bio-kemal-sahin.html',              categories: ['Biographies', 'Ottoman Empire', 'Grand Viziers', 'New Ottoman Era'],                                                             blurb: 'Ottoman military officer and Grand Vizier (1917–c.1927); led the restorative coup that ended the Karahan Interlude; principal architect of the New Ottoman Era\'s pan-Ottoman nationalist project; negotiated the Istanbul Accord (1919).' },
  { title: 'Mahmud III',                           file: 'bio-mahmud-3.html',            categories: ['Biographies', 'Ottoman Empire', 'Sultans', 'New Ottoman Era'],                                                                   blurb: '37th Sultan of the Ottoman Empire (from 1917); born Şehzade Mehmed Ziyaeddin; ascended following Kemal Şahin\'s restorative coup; physician, musician, and pan-Ottoman idealist; presided over the New Ottoman Era\'s foundational decade.' },
  
  // ── BIOGRAPHIES — US PRESIDENTS ──
  { title: 'George Washington',                    file: 'george-washington.html',      categories: ['Biographies', 'Presidents of the United States', 'Unaffiliated politicians', 'Founding Era'],                                    blurb: 'First President of the United States (1789–1797); established the precedents of the office.' },
  { title: 'John Adams',                           file: 'john-adams.html',             categories: ['Biographies', 'Presidents of the United States', 'Federalist Party politicians', 'Founding Era'],                                blurb: 'Second President of the United States (1797–1801); first Federalist president.' },
  { title: 'Thomas Jefferson',                     file: 'thomas-jefferson.html',       categories: ['Biographies', 'Presidents of the United States', 'Democratic-Republican politicians', 'Founding Era'],                           blurb: 'Third President of the United States (1801–1809); Louisiana Purchase and Lewis & Clark Expedition.' },
  { title: 'James Madison',                        file: 'james-madison.html',          categories: ['Biographies', 'Presidents of the United States', 'Democratic-Republican politicians', 'Founding Era'],                           blurb: 'Fourth President of the United States (1809–1817); president during the Burning of Washington City in 1814.' },
  { title: 'William Crawford',                     file: 'william-crawford.html',       categories: ['Biographies', 'Presidents of the United States', 'Democratic-Republican politicians', 'Founding Era'],                           blurb: 'Fifth President of the United States (1817–1821); oversaw the founding of Franklin as the new national capital.' },
  { title: 'Henry Clay',                           file: 'henry-clay.html',             categories: ['Biographies', 'Presidents of the United States', 'Democratic Party politicians', 'Founding Era'],                                  blurb: 'Sixth President of the United States (1821–1827); commissioned Washington House and established the Federal Bureau of Improvements.' },
  { title: 'Alexander Hamilton, Jr.',              file: 'alexander-hamilton-jr.html',  categories: ['Biographies', 'Presidents of the United States', 'Federalist Party politicians', 'Founding Era'],                                blurb: 'Seventh President of the United States (1827–1833); first president to reside in Washington House; oversaw the Franklin Indian Treaty.' },
  { title: 'John C. Calhoun',                      file: 'john-c-calhoun.html',         categories: ['Biographies', 'Presidents of the United States', 'Republican Party politicians', 'Republican Era'],                              blurb: 'Eighth President of the United States (1833–1836); established the USRC and the Preston education system; assassinated May 9, 1836.' },
  { title: 'Giles Brandon',                        file: 'giles-brandon.html',          categories: ['Biographies', 'Presidents of the United States', 'Republican Party politicians', 'Republican Era'],                              blurb: 'Ninth President of the United States (1836–1839); succeeded to office following the assassination of Calhoun; negotiated the First Treaty of New Orleans.' },
  { title: 'Victor Yates',                         file: 'victor-yates.html',           categories: ['Biographies', 'Presidents of the United States', 'Democratic Party politicians', 'Republican Era'],                                blurb: 'Tenth President of the United States (1839–1845); passed the Grantham Act and oversaw the admission of Iowa; declared war on Imperial Mexico in 1845.' },
  { title: 'Wilbur Haines',                        file: 'wilbur-haines.html',          categories: ['Biographies', 'Presidents of the United States', 'Democratic Party politicians', 'Republican Era'],                                blurb: 'Eleventh President of the United States (1845–1851); won the Second Mexican War, securing independence for Texas and California via the Second Treaty of New Orleans.' },
  { title: 'Robert Lee',                           file: 'robert-lee.html',             categories: ['Biographies', 'Presidents of the United States', 'Republican Party politicians', 'Republican Era'],                              blurb: 'Twelfth President of the United States (1851–1856); presided over escalating tensions over slavery and the Runaway Slave Act; assassinated in 1856.' },
  { title: 'James Hawthorne',                      file: 'james-hawthorne.html',        categories: ['Biographies', 'Presidents of the United States', 'Republican Party politicians', 'War Between the States'],                      blurb: 'Thirteenth President of the United States (1856–1860); his authoritarian response to abolitionist resistance triggered the War Between the States; surrendered in Atlanta in 1860.' },
  { title: 'Hugo Brandt',                          file: 'hugo-brandt.html',            categories: ['Biographies', 'Presidents of the United States', 'Democratic Party politicians', 'War Between the States'],                        blurb: 'Fourteenth President of the United States (1863–1869); Acting President of the Free States (1858–1863); led the republic through the War Between the States and the Reconstruction era.' },
  { title: 'John P. Quincy',                       file: 'john-p-quincy.html',          categories: ['Biographies', 'Presidents of the United States', 'Democratic Party politicians', 'Reconstruction'],                                blurb: 'Fifteenth President of the United States (1869–1873); oversaw the final reintegration of Georgia and Florida, established the Federal Office of Education, and completed the transcontinental railroad.' },
  { title: 'Bradley Kinder',                       file: 'bradley-kinder.html',         categories: ['Biographies', 'Presidents of the United States', 'Democratic Party politicians', 'Reconstruction'],                                blurb: 'Sixteenth President of the United States (1873–1875); caretaker president following the resignation of President Quincy in the wake of the Clark Scandal.' },
  { title: 'Horace Littlefield',                   file: 'horace-littlefield.html',     categories: ['Biographies', 'Presidents of the United States', 'Federalist Party politicians', 'Gilded Age'],                                  blurb: 'Seventeenth President of the United States (1877–1881); birth of the modern presidency — the first president to travel extensively, seeing the Pacific Coast and visiting Canada.' },
  { title: 'Theodore Drake',                       file: 'theodore-drake.html',         categories: ['Biographies', 'Presidents of the United States', 'Democratic Party politicians', 'Gilded Age'],                                  blurb: 'Eighteenth President of the United States (1881–1887); major austerity cuts; presided over — and failed to respond adequately to — the Italian Flu epidemic.' },
  { title: 'Leeland Rowling',                      file: 'leeland-rowling.html',        categories: ['Biographies', 'Presidents of the United States', 'Federalist Party politicians', 'Gilded Age'],                                  blurb: 'Nineteenth President of the United States (1887–1893); end of austerity, major expansions to the National Road network, the dedication of the Freedom Triumphant statue, and the first state visit to Great Britain.' },
  { title: 'Colin Beck',                           file: 'colin-beck.html',             categories: ['Biographies', 'Presidents of the United States', 'Federalist Party politicians', 'Gilded Age'],                                  blurb: 'Twentieth President of the United States (1893–1899); cabinet expansion, Women\'s suffrage amendment passed by Congress, and Calumet given federal district status.' },
  { title: 'Alexander Fleak',                      file: 'alexander-fleak.html',        categories: ['Biographies', 'Presidents of the United States', 'Federalist Party politicians', 'Gilded Age'],                                  blurb: 'Twenty-first President of the United States (1899–1903); continued support for infrastructure projects, major education reform, adoption of the suffrage amendment.' },
  { title: 'Peter Landon',                         file: 'peter-landon.html',           categories: ['Biographies', 'Presidents of the United States', 'Federalist Party politicians', 'Gilded Age', 'Wars and Conflicts'],            blurb: 'Twenty-second President of the United States (1903–1905); first Black man to serve as president; attempted to oversee the growing crisis in Cuba with the Matanzas Clique.' },
  { title: 'Cornelius Roosevelt II',               file: 'cornelius-roosevelt-ii.html', categories: ['Biographies', 'Presidents of the United States', 'Democratic Party politicians', 'Gilded Age', 'Wars and Conflicts'],            blurb: 'Twenty-third President of the United States (1905–1911); popular wartime president who oversaw the destruction of the Matanzas Clique in Cuba and a wave of postwar national pride.' },

];

// ── DERIVED DATA ──

// All unique categories, sorted
const NEDEX_CATEGORIES = [...new Set(NEDEX_ARTICLES.flatMap(a => a.categories))].sort();

// Articles grouped by primary category (first category listed)
function getNedexByCategory(cat) {
  return NEDEX_ARTICLES.filter(a => a.categories.includes(cat));
}

// Total article count
const NEDEX_COUNT = NEDEX_ARTICLES.length;

// Recent articles (last N added — assumes array is in chronological order)
function getNedexRecent(n = 5) {
  return [...NEDEX_ARTICLES].reverse().slice(0, n);
}

// ── FEATURED ARTICLE POOL ──
// Rotates daily using seeded shuffle so all articles appear before repeating.
const NEDEX_FEATURED = [
  {
    title: 'Hugo Brandt',
    file: 'hugo-brandt.html',
    img: '../../images/nedex/14-Photo-Brandt.png',
    summary: 'Hugo Brandt (1812–1891) is regarded by historians as one of the most consequential figures in American history — the man who held the republic together during the War Between the States, guided it through the abolition of slavery, and oversaw the constitutional convention that produced the Constitution of 1861. Born to German immigrant parents in Ohio, he became the youngest-ever Speaker of the House before leading the Free States government to victory.'
  },
  {
    title: 'Kingdom of Hawaiʻi',
    file: 'hawaii.html',
    img: '../../images/nedex/hawaii.png',
    subtitle: 'Unitary constitutional monarchy · Pacific Ocean',
    summary: 'The Kingdom of Hawaiʻi is one of the Pacific\'s preeminent trade and transit states, its capital Honolulu serving as the central waypoint on trans-Pacific routes connecting North America and East Asia. Governed by the Kamehameha Dynasty under a bicameral legislature, the kingdom navigated a century of foreign commercial pressure and emerged as a full member of the North American Union.'
  },
  {
    title: 'Union of European Republics',
    file: 'uer.html',
    img: '../../images/nedex/uerflag.png',
    subtitle: 'Communalist federal republic · Founded 1904',
    summary: 'The Union of European Republics was born from the simultaneous revolutionary collapse of France and the South German Confederation at the close of the Great European War. The only functioning communalist state in the world, it has been a source of ideological anxiety for conservative governments since its founding, and its survival against Prussian invasion in the Global War demonstrated that the experiment was not a passing moment but a durable state.'
  },
  {
    title: 'Federal Republic of Central America',
    file: 'central-america.html',
    img: '../../images/nedex/frca_flag.png',
    subtitle: 'Federal presidential republic · Founded 1830',
    summary: 'The Federal Republic of Central America is the only successful federation to emerge from the dissolution of Spanish colonial authority in Central America. Its survival across two centuries is widely attributed to Francisco Morazán\'s political pragmatism in negotiating the Federal Compact of 1836, which defused conservative opposition without sacrificing the federal framework. The republic became a key partner in the construction of the Central American Canal, opened in 1926.'
  },
  {
    title: 'Empire of Mexico',
    file: 'mexico.html',
    img: '../../images/nedex/mexico.png',
    subtitle: 'Constitutional monarchy · Founded 1835',
    summary: 'The Empire of Mexico was founded in 1835 following a conservative counter-coup against the liberal Mexican Republic. After decades of tension between throne and legislature, Empress Gabriella emerged victorious from a devastating civil war (1913–1921), and the Constitution of 1922 established genuine parliamentary democracy and universal suffrage — making Mexico one of the first nations in the world to grant women the vote.'
  },
  {
    title: 'William Crawford',
    file: 'william-crawford.html',
    img: '../../images/nedex/5-Crawford.png',
    summary: 'William Crawford holds a unique place in American history as the president who oversaw the founding of Franklin and the construction of the new national capital on the Ohio River. Governing in the aftermath of the burning of Washington City in August 1814, Crawford navigated the extraordinary challenge of relocating a federal government and establishing a new seat of power from which all subsequent American history would unfold.'
  },
];

// ── DID YOU KNOW POOL ──
// 40 entries — shuffled daily so all appear before repeating.
const NEDEX_DYK = [
  // Franklin & the capital
  'Washington House, the official residence of the President of the United States, was designed by architects Kemp & Ogden and completed in 1827 — its first occupant was President Alexander Hamilton Jr., son of Founding Father Alexander Hamilton.',
  'The city of Franklin was renamed from Cincinnati after President Crawford\'s 1817 Grand Compromise selected it as the new national capital — construction of the government district took a full decade, with the Congress Hall only completed in time for Hamilton\'s 1827 inauguration.',
  'Franklin is built on both banks of the Ohio River, with Congress Hall on the north bank and Washington House on the south. The George Washington Bridge linking the two sides of Union Avenue did not open until 1877 — fifty years after the city became the capital.',
  'Hugo Brandt\'s father was a stonemason who helped build Congress Hall in the 1820s — the same building Brandt would later govern from as Acting President of the Free States.',

  // War Between the States
  'The War Between the States produced not two but three rival governments at its peak: James Hawthorne\'s Union in Atlanta, Hugo Brandt\'s Free States in Philadelphia (later Franklin), and Ulysses Portman\'s Confederation of American States in Montpelier, Vermont.',
  'The shelling of Boston Harbor in early 1857 — when Union Navy ships misread a warning shot from Fort Warren as an attack — is widely credited with transforming what might have been a political standoff into a shooting war.',
  'Manhattan Island was fought over in three separate battles during the War Between the States, leaving it almost entirely destroyed. Its population fell from nearly half a million before the war to an estimated 75,000 by 1863, with European immigrants providing much of the labor force for its subsequent reconstruction.',
  'President Hawthorne relocated the Union government from Franklin to Atlanta in July of 1859, citing personal safety — a move his own generals opposed and which many historians regard as the moment the South lost the initiative.',
  'Joshua Black, a formerly enslaved house attendant from Mississippi, led a slave revolt in early 1860 that grew into the Republic of New Africa — controlling much of Mississippi and northern Alabama before ultimately agreeing to rejoin the United States in exchange for the Negro Emancipation Act of 1860.',
  'The Confederation of American States, formed by the New England secessionists, operated under a Westminster-style parliamentary constitution — meaning that when the Confederation dissolved and rejoined the United States in 1861, it brought with it the political ideas that shaped the executive reforms of the Constitution of 1861.',

  // Constitution of 1861
  'The Constitution of 1861 moved the Bill of Rights to the front of the document as Article I, explicitly defining citizenship and banning slavery — a reversal of the 1787 convention\'s decision not to lead with a list of rights.',
  'The office of Secretary General — the head of the president\'s cabinet, appointed by and accountable to the House of Representatives — was the most radical innovation of the 1861 Constitutional Convention, and the result of weeks of standoffs between New England delegates and moderates from the western states.',
  'Indiana Senator Abraham Lincoln presided over the 1861 Constitutional Convention, chosen as a moderate compromise between radical New Englanders and conservative southern delegates. He later became Chief Justice of the Supreme Court under President Quincy.',
  'The states of Kanasaw and Gigadohi — the first Native-majority states in the United States — were admitted to the Union in September of 1862, with constitutions that included a "Council of Nations" upper chamber representing each tribe and communal land trust provisions.',

  // The USRC & infrastructure
  'The USRC, founded in 1834 under President Calhoun, is one of the oldest continuously operating federal enterprises in the United States, predating the Constitution of 1861 itself — its first test line ran from Boston to Brooklyn.',
  'The National Road network was established under President Clay in 1821, beginning as a single route from Cumberland to Wheeling before eventually expanding to seven numbered roads spanning the continent. The Fifth National Road, from St. Louis to Astoria, Oregon, became the backbone of America\'s transcontinental connection.',
  'Canada\'s Trans-Canadian Railway and the United States\' transcontinental railroad were built in deliberate competition during the 1860s and 1870s, with newspapers on both sides of the border tracking construction progress in what they called "the Race to the Pacific."',

  // Presidents & political history
  'John C. Calhoun, the eighth President of the United States, was assassinated on May 9, 1836 — the first US president to be killed in office. His death set in motion the political crisis that would eventually lead to the War Between the States.',
  'President Robert Lee owned over a hundred enslaved people at the time he took office in 1851, yet wrote privately that he hoped to keep the presidency above the slavery debate and seek a lasting compromise — a goal that proved impossible.',
  'George Washington\'s decision not to seek a third term established the precedent of the two-term presidency — a tradition that was later codified in law under the Constitution of 1861.',
  'The election of 1826 was the second in American history to be decided by the House of Representatives, after no candidate won an outright majority of the electoral college. Alexander Hamilton Jr. was chosen despite John C. Calhoun receiving the most electoral votes — a result Republicans called the "Devil\'s Bargain."',
  'Peter Landon, the twenty-second president, was the first Black man to serve as President of the United States — elected in 1903 as the Federalist candidate at a moment when the party\'s abolitionist legacy gave it particular strength among Black voters in the South.',

  // Crawford era & Grand Compromise
  'The Grand Compromise of 1817 settled four major disputes at once: replacing Vice President Tompkins (who had died before the inauguration), moving the capital westward, reforming the presidential term to a single six-year period, and setting a higher threshold for declarations of war.',
  'The 14th Amendment, passed as part of the Grand Compromise of 1817, limited presidents to a single six-year term — a provision that shaped American politics for generations and prevented the emergence of entrenched executive dynasties.',

  // Hawaii
  'The Kingdom of Hawaiʻi\'s Constitution of 1868 created a bicameral legislature that included property-qualified seats originally designed to give formal representation to the kingdom\'s substantial foreign landowning community while preserving Hawaiian political authority.',
  'Honolulu\'s strategic importance as a trans-Pacific waypoint surged dramatically in the early 1880s when three separate transcontinental rail networks — American, Canadian, and Californian-Texian — all reached Pacific ports within a few years of each other, tripling the volume of shipping that needed a mid-ocean stop.',

  // California & Texas
  'The Union of the Californias declared independence in 1844 during the collapse of the Mexican Republic, but formal international recognition did not come until the Second Treaty of New Orleans in 1847, following the Second Mexican War.',
  'The Texas Federation\'s constitution of 1847 left slavery as a state-level issue — meaning only the state of Austin initially permitted it, while the other member states immediately banned the institution. Austin finally abolished slavery through compensated manumission in 1863 under pressure from both Texopolis and Franklin.',
  'The Galvezport-to-San Francisco railroad, completed in 1881 and funded jointly by the Texas Federation and the Union of the Californias, was the first rail link across the southern span of the North American continent and transformed both nations\' economies within a decade.',

  // Canada
  'Canada\'s capital Aurora was purpose-built on Manitoulin Island in Lake Huron as a compromise between Toronto and Montreal interests — construction began in the mid-1880s and it became the seat of government in the early 1900s.',
  'The Dominion of Canada was formed in 1864 partly in response to the United States\' transcontinental railroad ambitions — colonial leaders recognized that only a unified British North America could pool the resources needed to build a competing line from Toronto to the Pacific coast.',

  // Mexico & FRCA
  'The Empire of Mexico\'s Empress Gabriella came to power in 1913 at the age of 26, and within months was fighting a civil war against her own brother, who had declared himself Emperor Raul IV. She prevailed and went on to enact universal suffrage in 1922.',
  'The Central American Canal, opened in 1926, was built under a tripartite commission representing the United States, the Federal Republic of Central America, and Canada — with canal toll revenues divided roughly equally among the three signatories of the Treaty of Managua.',
  'The Federal Republic of Central America\'s founding president, Francisco Morazán, negotiated the Federal Compact of 1836 — conceding provincial autonomy and Church property rights to conservatives in exchange for the federation\'s survival. He governed for over two decades and died in office in 1856.',

  // UER & European history
  'The Union of European Republics commissioned a constructed language — Europan — under First Delegate Mathias Holtz, intended to dissolve national identities by replacing French and German as the medium of official life. It survives today in ceremonial use only.',
  'Mathias Holtz, the UER\'s second First Delegate, moved the capital from Paris to Strasbourg in 1916 as a symbolic gesture of neutrality between the French and German founding peoples — it was moved back to Paris after his removal from power in the late 1920s.',
  'The UER\'s 1906 repudiation of all pre-revolutionary French and South German debt caused a cascading financial crash across European institutions — a deliberate gamble by First Delegate Marchand, who calculated that diplomatic isolation was preferable to servicing debts of governments the UER had overthrown.',

  // Germany & Prussia
  'When the United German Republic was proclaimed in 1938, it was built from the non-Prussian states of the old Union of German States — Hanover, Thuringia, Saxony, Hamburg, and others. The Kingdom of Prussia limped on separately for another five decades before collapsing in the 1990s.',
  'The young Prussian king Franz Hohenzollern, who died during a coup attempt in 1995, never lived to see the unified Germany his martyrdom made possible. Statues, public squares, and a national scholarship program across the reunified republic now bear his name.',
  'Hannover was chosen as the capital of the United German Republic in 1938 in deliberate rejection of Berlin — the founders wanted to signal that the Germany built on resistance to Prussian domination, not Prussian imperial ambition, was the Germany that would now govern itself.',
];

// ── SEEDED SHUFFLE ──
// Deterministic Fisher-Yates using a simple LCG seeded by day-of-year.
// Ensures all items appear before repeating across a full cycle.
function _nedexSeededShuffle(arr, seed) {
  const a = arr.slice();
  let s = seed;
  for (let i = a.length - 1; i > 0; i--) {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    const j = Math.abs(s) % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

const _nedexDayOfYear = Math.floor((new Date() - new Date(new Date().getFullYear(), 0, 0)) / 86400000);

// Featured article: cycles through all entries before repeating
const _nedexFeaturedShuffled = _nedexSeededShuffle(NEDEX_FEATURED, _nedexDayOfYear + 1);
const NEDEX_FEATURED_TODAY = _nedexFeaturedShuffled[_nedexDayOfYear % _nedexFeaturedShuffled.length];

// DYK: shuffled daily, pick first 3 — full 40-item cycle before any repeat
const _nedexDYKShuffled = _nedexSeededShuffle(NEDEX_DYK, _nedexDayOfYear + 7);
const NEDEX_DYK_TODAY = _nedexDYKShuffled.slice(0, 3);
