// content.js — Washington Burns Timeline shared content index
// Single source of truth for all searchable site content
// Used by: Waymark search (index.html), and eventually each node page
// ─────────────────────────────────────────────────────────────────────

// ── FEDERAL PARKS ──────────────────────────────────────────────────────
const WBT_PARKS = [
  { id: 'smokies', name: 'Great Smokies Federal Park', location: 'Tennessee · North Carolina', region: 'east', img: '../../images/parks/smokes.jpg', tags: ['Hiking','Wildlife','Camping','Heritage'], desc: 'Ancient Appalachian highlands protecting over 800 square miles of old-growth forest and one of the most biodiverse temperate ecosystems in the world.', lat: 35.6532, lon: -83.5070, tz: 'America/New_York', trails: ['All primary trails open', 'Clingmans Dome Road seasonal closure check advised', 'Backcountry permits required for overnight'], tips: ['Arrive before 9 a.m. to secure parking at popular trailheads — crowds build quickly after mid-morning.', 'Bring layers even in summer — temperatures at elevation can drop 20°F below the valley floor.', 'The Appalachian Trail runs through the park — long-distance hikers should register at the visitor centre.'] },
  { id: 'crater', name: 'Crater Lake Federal Park', location: 'Oregon', region: 'pnw', img: '../../images/parks/crater.jpg', tags: ['Volcanic','Water','Geology','Winter Sports'], desc: 'Formed by the collapse of ancient Mount Mazama, Crater Lake is the deepest lake in the United States — renowned for the extraordinary clarity and blue intensity of its waters.', lat: 42.9446, lon: -122.1090, tz: 'America/Los_Angeles', trails: ['Rim Drive open seasonally — check FPS alerts', 'Cleetwood Cove Trail (lake access) open summer only', 'Wizard Island boat tours — advance booking required'], tips: ['The Rim Village visitor centre has excellent exhibits on the eruption that created the lake — worth 30 minutes before hitting the trails.', 'Sunrise on the east rim offers the clearest water colour — afternoon haze can reduce visibility.', 'Snow can fall at any month at the rim elevation — always carry a layer.'] },
  { id: 'capitol', name: 'First Capital Federal Park', location: 'Maryland', region: 'east', img: '../../images/parks/capitol_ruins.png', tags: ['Heritage','History','Memorial','Walking'], desc: 'Preserved on the Potomac, this park encompasses the ruins and grounds of the original federal city destroyed in August 1814 — a solemn memorial to the founding era.', lat: 38.8951, lon: -77.0364, tz: 'America/New_York', trails: ['Heritage Walk open daily', 'Ruins viewing platforms accessible year-round', 'Ranger-led tours available weekends May–October'], tips: ['The ranger-led Burning Night walk (offered Friday evenings in summer) is the most moving way to experience the site — book ahead.', 'The visitor centre film "August 1814" is only 18 minutes and adds enormous context before walking the ruins.', 'The park is particularly atmospheric in the early morning before the tour groups arrive.'] },
  { id: 'sacred', name: 'Sacred Waters Federal Park', location: 'Washingtonia · Clark', region: 'mw', img: '../../images/parks/sacred.jpg', tags: ['Geothermal','Wildlife','Wilderness','Camping'], desc: "Home to the world's largest concentration of geysers, hot springs, and hydrothermal features, straddles one of the most geologically active regions on the continent.", lat: 44.4280, lon: -110.5885, tz: 'America/Denver', trails: ['Boardwalk trails open year-round', 'Backcountry routes may be snow-covered — check conditions', 'Wildlife viewing corridors open — bison right-of-way always'], tips: ['Old Thunderhead geyser erupts approximately every 91 minutes — check the prediction board at the visitor centre on arrival.', 'Stay on boardwalks near thermal features — ground crusts can be dangerously thin.', 'Bison have the right of way on all park roads and trails — keep 25 metres minimum distance.'] },
  { id: 'mistakis', name: 'Mistakis Federal Park', location: 'Washingtonia · Clark', region: 'mw', img: '../../images/parks/glacier.jpg', tags: ['Alpine','Glaciers','Wildlife','Hiking'], desc: 'Named for the Blackfoot word for "backbone of the world," Mistakis preserves a dramatic landscape of glacially carved peaks, alpine meadows, and pristine wilderness.', lat: 48.6962, lon: -113.7180, tz: 'America/Denver', trails: ['Going-to-the-Sun Road open seasonally — check FPS alerts', 'Many high trails snow-covered before July', 'Bear spray required for backcountry travel'], tips: ['Vehicle reservations required for Going-to-the-Sun Road during peak season — book at least 60 days ahead.', 'Grizzly bear activity is common — carry bear spray and know how to use it before entering backcountry.', 'The Highline Trail is one of the finest day hikes in the country — attempt it early to beat afternoon thunderstorms.'] },
  { id: 'wyeast', name: "Wy'east Federal Park", location: 'Oregon', region: 'pnw', img: '../../images/parks/hood.jpg', imgPos: 'center top', tags: ['Volcanic','Alpine','Climbing','Winter Sports'], desc: "Known by its Multnomah name long before statehood, Wy'east is a stratovolcano rising above the Oregon forests to over 11,000 feet, offering year-round recreation.", lat: 45.3735, lon: -121.6960, tz: 'America/Los_Angeles', trails: ['Timberline Trail open summer — upper sections require mountaineering gear', 'Mirror Lake Trail open year-round', 'Summit climbs require climbing permits'], tips: ['Timberline Lodge is a marvel of Depression-era craftsmanship — worth a visit even if you are not climbing.', 'Summit attempts should begin before 3 a.m. to complete the climb before afternoon ice softens dangerously.', 'The wildflower meadows around timberline peak in late July — stunning for photography.'] },
  { id: 'silver', name: 'Silver Creek Federal Park', location: 'Oregon', region: 'pnw', img: '../../images/parks/silver_falls.jpg', tags: ['Waterfalls','Hiking','Old Growth','Family'], desc: 'A jewel of the Oregon lowlands, Silver Creek protects a remarkable concentration of waterfalls — ten major falls within a few miles of trail, including several walk-behind cascades.', lat: 44.8774, lon: -122.6548, tz: 'America/Los_Angeles', trails: ['Trail of Ten Falls open year-round', 'Some trails slippery when wet — traction devices recommended in winter', 'Canyon Trail accessible year-round'], tips: ['Wear waterproof clothing for the walk-behind falls — you will get wet regardless of the weather.', 'The Trail of Ten Falls loop is 13 km — most families complete it in 4-5 hours with stops at each fall.', 'Autumn colour peaks in mid-October and the falls run strongest in winter and spring.'] },
  { id: 'cascades', name: 'Cascades International Park', location: 'Oregon · California', region: 'pnw', img: '../../images/parks/shasta.jpg', tags: ['Volcanic','International','Alpine','Wilderness'], desc: 'A joint USA-California Federal Park protecting the volcanic spine of the Cascade Range, including Mt. Shasta, Mt. McLaughlin, and the Three Sisters.', lat: 41.4092, lon: -122.1949, tz: 'America/Los_Angeles', trails: ['Lower trails open year-round', 'High routes require mountaineering experience and permits', 'Shasta summit climbs — permit required, check volcanic activity alerts'], tips: ['Mt. Shasta is one of the most volcanically active peaks in the range — check FPS volcano alerts before summit attempts.', 'The cross-border nature of the park means USA and California passes are both honoured — check your pass validity at the trailhead station.', 'Castle Lake, just outside the park boundary, offers excellent fishing and swimming in a dramatically scenic setting.'] },
];

// ── NAU ASSEMBLY BILLS ─────────────────────────────────────────────────
const WBT_BILLS = [
  { num: 'NAU/18-042', title: 'Continental Currency Stabilisation Framework Act', desc: 'Establishes a binding framework to harmonise exchange arrangements across all thirteen member states and codifies the role of the Continental Bank in monetary oversight. Backed by a Labour-Unionist majority.', status: 'floor', statusLabel: 'On Floor', sponsor: 'Mbr. Okafor (Lab.-USA), Mbr. Tremblay (Un.-Canada), Mbr. Reyes (Lab.-Mexico)' },
  { num: 'NAU/18-031', title: 'NAU Constitutional Consolidation Act', desc: 'Consolidates sixty years of accumulated treaties, charter revisions, and amendments into a single founding document. Formally establishes NAU citizenship alongside member-state citizenship and creates a permanent NAU judiciary. Mexico has reserved its position pending review of the judiciary provisions.', status: 'committee', statusLabel: 'Constitutional Committee', sponsor: 'Mbr. Halverson (Un.-USA), Mbr. Dumont (Lab.-Canada), Mbr. Castillo (Un.-California)' },
  { num: 'NAU/18-019', title: 'Pan-Continental Clean Waters Compact', desc: 'Establishes binding water quality standards across shared river systems, coastal zones, and the Great Lakes basin. Includes enforcement mechanisms and a joint monitoring agency. Led by the Greens with Labour support; CC bloc opposed on sovereignty grounds.', status: 'passed', statusLabel: 'Passed Committee', sponsor: 'Mbr. Kahananui (Grn.-Hawaii), Mbr. Beaumont (Grn.-Canada), Mbr. Flores (Lab.-FRCA)' },
  { num: 'NAU/18-008', title: 'Caribbean Integration & Development Fund Reauthorisation', desc: "Reauthorises and expands the Fund established at Caribbean member states' accession, providing infrastructure, education, and economic development support. Broad cross-bloc support expected.", status: 'committee', statusLabel: 'Development Committee', sponsor: 'Mbr. Saint-Fleur (Lab.-Haiti), Mbr. Morales (Un.-Dominican Rep.), Mbr. Chen (Un.-California)' },
  { num: 'NAU/18-055', title: 'Pacific Trade Framework Renewal Act', desc: 'Renews and expands the bilateral trade frameworks governing NAU relations with Japan, China, and the Kingdom of Hawaii. Introduces new provisions on digital trade, intellectual property, and supply chain resilience. Strong Unionist and Labour backing.', status: 'floor', statusLabel: 'On Floor', sponsor: 'Mbr. Nakashima (Un.-USA), Mbr. Kahananui (Grn.-Hawaii), Mbr. Dumont (Lab.-Canada)' },
  { num: 'NAU/18-061', title: 'NAU Civil Aviation Standards Harmonisation Act', desc: 'Brings all thirteen member states under a single set of safety standards, licensing requirements, and air traffic management protocols. Technical legislation with broad support across all blocs.', status: 'committee', statusLabel: 'Transport Committee', sponsor: 'Mbr. Lavigne (Un.-Canada), Mbr. Torres (Lab.-Mexico), Mbr. Williams (CC-USA)' },
  { num: 'NAU/18-037', title: 'Interlink Access Equity Resolution', desc: 'Non-binding resolution calling on all member states to achieve universal household Interlink access by 2030 and to remove restrictions on cross-border data flows within the NAU. Greens and Labour co-sponsored; CC bloc abstaining.', status: 'passed', statusLabel: 'Passed — Non-binding', sponsor: 'Mbr. Beaumont (Grn.-Canada), Mbr. Okafor (Lab.-USA), Mbr. Reyes (Lab.-Mexico)' },
  { num: 'NAU/18-044', title: 'Mutual Recognition of Professional Qualifications Act', desc: 'Requires all member states to recognise professional qualifications — medical, legal, engineering, and teaching — issued by any other member state. Contentious among some provincial governments; Unionist bloc divided.', status: 'committee', statusLabel: 'Legal Affairs Committee', sponsor: 'Mbr. Castillo (Un.-California), Mbr. Vasquez (Lab.-Mexico), Mbr. Tremblay (Un.-Canada)' },
];

// ── NAU ASSEMBLY FLOOR BANNERS ─────────────────────────────────────────
const WBT_FLOOR_BANNERS = [
  { label: 'Assembly Floor — Now in Debate', bill: 'NAU/18-042 — Continental Currency Stabilisation Framework', meta: 'Second reading · Economic Affairs Committee · Debate in progress · Est. vote: 15:00 Calumet Time' },
  { label: 'Assembly Floor — Second Reading', bill: 'NAU/18-031 — NAU Constitutional Consolidation Act', meta: 'Constitutional Committee report tabled · General debate open · No vote scheduled today' },
  { label: 'Assembly Floor — Committee Stage', bill: 'NAU/18-019 — Pan-Continental Clean Waters Compact', meta: 'Line-by-line review · Environment & Sustainability Committee · Session resumes 10:00 Calumet Time' },
  { label: 'Assembly Floor — Question Time', bill: 'Assembly Questions to the Executive Council', meta: 'Members may submit written questions · Oral questions: 14:00-16:00 Calumet Time' },
  { label: 'Assembly Floor — Procedural Session', bill: 'NAU/18-008 — Caribbean Integration & Development Fund Reauthorisation', meta: 'First reading · Referred to Development Committee · No debate scheduled' },
  { label: 'Assembly Floor — Emergency Debate', bill: 'Motion on NAU Response to Mesopotamian Reconstruction Progress', meta: 'Tabled by Labour and Unionist blocs · Debate limited to 3 hours · Vote on motion expected' },
  { label: 'Assembly Floor — Now in Debate', bill: 'NAU/18-055 — Pacific Trade Framework Renewal', meta: 'Third reading · Trade & External Relations Committee · Vote expected 16:30 Calumet Time' },
];

// ── MUSEUM OF THE UNITED STATES ────────────────────────────────────────
const WBT_MUSEUM_GALLERIES = [
  { title: 'The American Presidency: From Washington to Nakamura', floor: 'Level 1 · East Wing', desc: "Two centuries of executive leadership — objects, documents, and portraits tracing every president from the republic's founding to the present day." },
  { title: 'Iron Nation: Two Centuries of American Rail', floor: 'Level 1 · West Wing', desc: 'From the founding of the USRC in 1834 to the modern high-speed network — the story of how rail shaped the American continent.' },
  { title: 'War Between the States, 1857–1860: The Crisis That Remade America', floor: 'Level 2 · Central Hall', desc: 'The defining conflict of the nineteenth century — from the collapse of the Hawthorne government to the Philadelphia Convention and the Constitution of 1861.' },
  { title: 'The Global War: America and the World, 1932–1940', floor: 'Level 2 · North Gallery', desc: "America's defining international conflict — from the first Prussian advances to the Treaty of Geneva and the founding of the Global Peace Council." },
  { title: 'Votes and Voices: Two Centuries of American Democracy', floor: 'Level 3 · South Gallery', desc: 'From the first elections under the 1787 Constitution to the Third Amendment and universal suffrage — the long arc of democratic participation in America.' },
  { title: 'American Arts & Material Culture, 1814–Present', floor: 'Level 3 · East Gallery', desc: 'Objects, artworks, and everyday items tracing American material life from the founding of Franklin to the present — furniture, fashion, fine art, and folk tradition.' },
];

const WBT_MUSEUM_EVENTS = [
  { title: "Curator's Talk: The August Letters — Objects from the 1814 Evacuation", time: '2:00 p.m.' },
  { title: 'Evening Lecture: Freeman and the Postwar Moment', time: '6:00 p.m.' },
  { title: 'Family Day: Rail Through History', time: '10:00 a.m.' },
  { title: 'Archives Gallery: Special Extended Hours — Document Conservation Week', time: '9:00 a.m.' },
  { title: 'Symposium: The 1861 Constitution and Its Legacy', time: '3:00 p.m.' },
  { title: 'School Group Day: War Between the States Gallery — Guided Tours', time: '9:30 a.m.' },
  { title: 'Film Screening: The Long March to Franklin (1962)', time: '7:00 p.m.' },
  { title: 'Lecture: The Global War Through American Eyes', time: '5:30 p.m.' },
];

// ── WASHINGTON HOUSE ───────────────────────────────────────────────────
const WBT_WH_STATEMENTS = [
  { label: 'Statement from the President', date: '13 March 2026', text: "\"The Assembly exists to debate these questions — that is precisely what it was designed to do. If the people's representatives, meeting the standard our Constitution demands, choose to open that conversation, I will not stand in their way.\"", attr: '— President Nakamura, on the NAU Constitutional Consolidation question · Office of Communications' },
  { label: 'Statement from the President', date: '8 March 2026', text: '"This is what public investment looks like. Generation after generation, the Railway Company has delivered — and these numbers prove that when we invest in our people, they show up."', attr: '— President Nakamura, on USRC Q1 ridership record · Office of Communications' },
  { label: 'Statement from the President', date: '24 February 2026', text: '"We enter these talks not to dominate, but to build — a North America where every nation, large or small, has an equal stake in our shared prosperity."', attr: '— President Nakamura, ahead of NAU Economic Summit · Office of Communications' },
  { label: 'Statement from the President', date: '18 February 2026', text: '"Clean water is not a regional issue. It is a continental one. The Great Lakes belong to all of us, and we will protect them together."', attr: '— President Nakamura, on the Pan-Continental Clean Waters Compact · Office of Communications' },
  { label: 'Statement from the President', date: '11 February 2026', text: '"One year ago, I stood on the steps of this House and asked the American people for their trust. I intend to spend the next five years earning it."', attr: '— President Nakamura, first anniversary address · Office of Communications' },
  { label: 'Statement from the President', date: '3 February 2026', text: '"The question before us is not whether we can afford to act on this — the question is whether we can afford not to."', attr: '— President Nakamura, on the federal clean energy investment package · Office of Communications' },
  { label: 'Statement from the Press Secretary', date: '10 March 2026', text: '"The President is monitoring the situation closely and has directed the relevant departments to provide a full assessment by end of week. We will have more to say when that review is complete."', attr: '— Press Secretary Delacroix · Morning Briefing' },
  { label: 'Statement from the President', date: '27 January 2026', text: "\"Pacific trade is not a privilege — it is the backbone of our Pacific states' economies, and it must be protected with clear-eyed, principled negotiation.\"", attr: '— President Nakamura, on Pacific Trade Framework renewal · Office of Communications' },
  { label: 'Statement from the President', date: '15 January 2026', text: '"Every park, every trail, every stretch of protected wilderness is a promise we keep to our children. Today we keep another."', attr: '— President Nakamura, at the Federal Parks designation ceremony · Office of Communications' },
  { label: 'Statement from the Press Secretary', date: '5 March 2026', text: "\"The President congratulates the USRC on another record quarter and reaffirms the Administration's commitment to continued federal investment in the national rail network.\"", attr: '— Press Secretary Delacroix · Office of Communications' },
];

const WBT_WH_BRIEFING = [
  { title: 'President Nakamura to Address NAU Economic Summit in Montreal, April 3-4', meta: 'Office of the Press Secretary · 12 March 2026' },
  { title: 'Statement on USRC Q1 Ridership Record: "A testament to what public investment delivers."', meta: 'Office of Communications · 8 March 2026' },
  { title: 'President Nakamura Receives Canadian Prime Minister Tremblay at Washington House', meta: 'Office of the Press Secretary · 7 March 2026' },
  { title: 'Administration Announces Appointments to the Federal Arbitration Bureau', meta: 'Office of the President · 5 March 2026' },
  { title: 'Nakamura Signs Reauthorisation of the Caribbean Integration & Development Fund', meta: 'Office of Communications · 3 March 2026' },
  { title: 'President Issues Statement Supporting NAU Assembly Currency Stabilisation Framework', meta: 'Office of Communications · 28 February 2026' },
  { title: 'Washington House West Wing Tours Resume Following Renovation of State Dining Room', meta: 'Office of the Press Secretary · 20 February 2026' },
  { title: 'President Nakamura Signs Pacific Trade Framework Renewal into Law', meta: 'Office of the Press Secretary · 25 February 2026' },
  { title: 'Administration Releases First Anniversary Progress Report — 47 Legislative Priorities', meta: 'Office of Communications · 11 February 2026' },
  { title: "President Nakamura Hosts State Dinner for Kingdom of Hawaii Queen's Representative", meta: 'Office of the Press Secretary · 18 February 2026' },
  { title: 'Nakamura Nominates Three Justices to the Federal Court of Appeals, Western Circuit', meta: 'Office of the President · 22 February 2026' },
  { title: 'Press Secretary Delacroix Addresses Questions on NAU Consolidation Timeline', meta: 'Office of Communications · 2 March 2026' },
  { title: 'President Nakamura Marks Anniversary of Great Lakes Environmental Compact', meta: 'Office of Communications · 15 March 2026' },
  { title: 'Administration Announces Federal Parks Expansion — Six New Protected Areas Designated', meta: 'Office of the Press Secretary · 15 January 2026' },
  { title: 'President Nakamura Delivers Remarks at National Science & Industry Exposition, Calumet', meta: 'Office of Communications · 10 January 2026' },
];
