// content.js — Washington Burns Timeline shared content index
// Single source of truth for all searchable site content
// ─────────────────────────────────────────────────────────────────────

// ── FEDERAL PARKS ──────────────────────────────────────────────────────
const WBT_PARKS = [

  // ── PACIFIC NORTHWEST ──
  { id: 'crater', name: 'Crater Lake Federal Park', location: 'Oregon', region: 'pnw', img: '/washington_burns/images/parks/crater.jpg', imgPos: 'center top', tags: ['Volcanic','Water','Geology','Winter Sports'], desc: 'Formed by the collapse of ancient Mount Mazama, Crater Lake is the deepest lake in the United States — renowned for the extraordinary clarity and blue intensity of its waters.', lat: 42.9446, lon: -122.1090, tz: 'America/Los_Angeles', trails: ['Rim Drive open seasonally — check FPS alerts', 'Cleetwood Cove Trail (lake access) open summer only', 'Wizard Island boat tours — advance booking required'], tips: ['The Rim Village visitor centre has excellent exhibits on the eruption that created the lake — worth 30 minutes before hitting the trails.', 'Sunrise on the east rim offers the clearest water colour — afternoon haze can reduce visibility.', 'Snow can fall at any month at the rim elevation — always carry a layer.'] },

  { id: 'wyeast', name: "Wy'east Federal Park", location: 'Oregon', region: 'pnw', img: '/washington_burns/images/parks/hood.jpg', imgPos: 'center top', tags: ['Volcanic','Alpine','Climbing','Winter Sports'], desc: "Known by its Multnomah name long before statehood, Wy'east is a stratovolcano rising above the Oregon forests to over 11,000 feet, offering year-round recreation.", lat: 45.3735, lon: -121.6960, tz: 'America/Los_Angeles', trails: ['Timberline Trail open summer — upper sections require mountaineering gear', 'Mirror Lake Trail open year-round', 'Summit climbs require climbing permits'], tips: ['Timberline Lodge is a marvel of Depression-era craftsmanship — worth a visit even if you are not climbing.', 'Summit attempts should begin before 3 a.m. to complete the climb before afternoon ice softens dangerously.', 'The wildflower meadows around timberline peak in late July — stunning for photography.'] },

  { id: 'silver', name: 'Silver Creek Federal Park', location: 'Oregon', region: 'pnw', img: '/washington_burns/images/parks/silver_falls.jpg', imgPos: 'center top', tags: ['Waterfalls','Hiking','Old Growth','Family'], desc: 'A jewel of the Oregon lowlands, Silver Creek protects a remarkable concentration of waterfalls — ten major falls within a few miles of trail, including several walk-behind cascades.', lat: 44.8774, lon: -122.6548, tz: 'America/Los_Angeles', trails: ['Trail of Ten Falls open year-round', 'Some trails slippery when wet — traction devices recommended in winter', 'Canyon Trail accessible year-round'], tips: ['Wear waterproof clothing for the walk-behind falls — you will get wet regardless of the weather.', 'The Trail of Ten Falls loop is 13 km — most families complete it in 4-5 hours with stops at each fall.', 'Autumn colour peaks in mid-October and the falls run strongest in winter and spring.'] },

  { id: 'cascades', name: 'Cascades International Park', location: 'Oregon · California', region: 'pnw', img: '/washington_burns/images/parks/shasta.jpg', imgPos: 'center top', tags: ['Volcanic','International','Alpine','Wilderness'], desc: 'A joint USA-California Federal Park protecting the volcanic spine of the Cascade Range, including Mt. Shasta, Mt. McLaughlin, and the Three Sisters.', lat: 41.4092, lon: -122.1949, tz: 'America/Los_Angeles', trails: ['Lower trails open year-round', 'High routes require mountaineering experience and permits', 'Shasta summit climbs — permit required, check volcanic activity alerts'], tips: ['Mt. Shasta is one of the most volcanically active peaks in the range — check FPS volcano alerts before summit attempts.', 'The cross-border nature of the park means USA and California passes are both honoured — check your pass validity at the trailhead station.', 'Castle Lake, just outside the park boundary, offers excellent fishing and swimming in a dramatically scenic setting.'] },

  { id: 'dunes', name: 'Oregon Dunes Federal Park', location: 'Oregon', region: 'pnw', img: '', imgPos: 'center top', tags: ['Coastal','Dunes','Wildlife','Hiking'], desc: 'The largest coastal sand dune system in North America, stretching over fifty miles along the Oregon coast. Wind-sculpted dunes rise as high as five hundred feet, interspersed with freshwater lakes, forests, and wetlands sheltering migratory shorebirds and rare plant communities.', lat: 43.9015, lon: -124.1557, tz: 'America/Los_Angeles', trails: ['Dune trail network open year-round — follow posts carefully', 'Freshwater lake swimming areas open seasonally', 'Horsfall Beach accessible year-round'], tips: ['The dunes shift constantly — trails are marked with posts rather than cleared paths. Follow them carefully or you will get turned around quickly.', 'Swimming is permitted in the freshwater lakes but not in the ocean — Pacific surf along this stretch is dangerously unpredictable.', 'The overlook at Jessie M. Honeyman is the best single viewpoint for understanding the scale of the dune system — start there before heading out on foot.'] },

  { id: 'tillamook', name: 'Tillamook Headlands Federal Park', location: 'Oregon', region: 'pnw', img: '', imgPos: 'center top', tags: ['Coastal','Cliffs','Wildlife','Scenic'], desc: 'A rugged stretch of the northern Oregon coast protecting dramatic sea stacks, forested headlands, and some of the most productive seabird nesting habitat on the Pacific coast. The park encompasses Cape Meares, Cape Lookout, and Cape Kiwanda, along with the Tillamook estuary.', lat: 45.4579, lon: -123.9650, tz: 'America/Los_Angeles', trails: ['Cape Lookout Trail open year-round', 'Cape Meares Loop open year-round', 'Estuary water trail open seasonally'], tips: ['Cape Lookout trail offers the most dramatic coastal views — a two-mile ridge walk with ocean on three sides at the point. Go early, as afternoon fog frequently obscures the view.', 'The sea stacks offshore are active nesting sites for tufted puffins and common murres from April through August — bring binoculars.', 'The Tillamook estuary section of the park is best explored by canoe or kayak — rentals available at the visitor centre.'] },

  { id: 'columbia_gorge', name: 'Columbia Gorge International Federal Park', location: 'Oregon · Canada', region: 'pnw', img: '', imgPos: 'center top', tags: ['International','Waterfalls','Scenic','Hiking'], desc: 'A joint USA-Canada Federal Park protecting the dramatic basalt canyon carved by the Columbia River through the Cascade Range. The park encompasses Crown Point, Multnomah Falls, and dozens of tributary waterfalls, along with the forested slopes of the Canadian Province of Columbia.', lat: 45.5762, lon: -122.1167, tz: 'America/Los_Angeles', trails: ['Historic Columbia River Highway open year-round', 'Multnomah Falls Trail open year-round', 'Crown Point Vista open seasonally'], tips: ['Multnomah Falls is the park signature landmark — arrive before 8 a.m. or after 5 p.m. to experience it without crowds.', 'The Historic Columbia River Highway on the Oregon side is one of the finest scenic drives in the NAU — the stonework viewpoints are engineering landmarks.', 'Canadian and USA Federal Parks passes are both honoured throughout the park — check signage at trailheads to confirm which jurisdiction you are entering.'] },

  { id: 'hells_canyon', name: 'Hells Canyon Federal Park', location: 'Clark', region: 'pnw', img: '', imgPos: 'center top', tags: ['Canyon','River','Wilderness','Rafting'], desc: "North America's deepest river gorge, carved by the Snake River along the Clark-Oregon border. At nearly eight thousand feet from rim to river, Hells Canyon exceeds even the Grand Canyon in depth, sheltering bighorn sheep, black bears, and one of the most important whitewater stretches on the continent.", lat: 45.4427, lon: -116.7000, tz: 'America/Los_Angeles', trails: ['Rim trails open seasonally — check conditions', 'River access by permit only', 'Snake River water trail open year-round'], tips: ['The canyon is most dramatically experienced from the river — multi-day rafting trips are among the finest wilderness river experiences in the NAU. Book well in advance.', 'Rim viewpoints on the Clark side are accessible by road — the Hat Point overlook at 6,982 feet offers the most vertiginous view into the canyon.', 'Rattlesnakes are common on lower canyon trails from April through October — watch where you step and where you put your hands.'] },

  { id: 'steens', name: 'Steens Mountain Federal Park', location: 'Clark', region: 'pnw', img: '', imgPos: 'center top', tags: ['Alpine','Desert','Wildlife','Wilderness'], desc: 'A dramatic fault-block mountain rising abruptly from the high desert of southeastern Clark, Steens Mountain reaches nearly ten thousand feet and creates its own weather system. The western slope rises gradually through sagebrush; the eastern face drops nearly five thousand feet into the Alvord Desert below.', lat: 42.6318, lon: -118.5750, tz: 'America/Los_Angeles', trails: ['Steens Mountain Loop Road open mid-July through October', 'East Rim Viewpoint Trail open seasonally', 'Alvord Desert access year-round'], tips: ['The Steens Mountain Loop Road is open only from mid-July through October — check FPS road conditions before making the drive.', 'The Alvord Desert at the mountain eastern base becomes a vast reflective playa after winter rains — extraordinary for photography in early spring.', 'Pronghorn antelope are commonly seen on the lower slopes — the largest herds typically appear in late summer.'] },

  { id: 'grand_teton', name: 'Grand Teton Federal Park', location: 'Clark', region: 'pnw', img: '', imgPos: 'center top', tags: ['Alpine','Wildlife','Scenic','Climbing'], desc: 'The Teton Range rises with almost no foothills from the flat floor of Jackson Hole valley, creating one of the most dramatic mountain frontages in North America. Grand Teton at 13,775 feet dominates a jagged skyline visible for fifty miles, with critical habitat for grizzly bears, wolves, elk, and bison in the broader Greater Sacred Waters ecosystem.', lat: 43.7904, lon: -110.6818, tz: 'America/Denver', trails: ['Jenny Lake Loop open seasonally', 'Cascade Canyon Trail open summer', 'Grand Teton summit — technical climbing permit required'], tips: ['The Snake River Overlook is the classic Teton viewpoint — visit at dawn for the best light and the calmest air.', 'Grand Teton itself is a serious mountaineering objective — the park climbing rangers offer orientation sessions for those planning summit attempts.', 'Wildlife is most active at dawn and dusk along the Oxbow Bend of the Snake River — moose, bald eagles, and beaver are reliably seen here year-round.'] },

  // ── MOUNTAIN WEST ──
  { id: 'sacred', name: 'Sacred Waters Federal Park', location: 'Washingtonia · Clark', region: 'mw', img: '/washington_burns/images/parks/sacred.jpg', imgPos: 'center top', tags: ['Geothermal','Wildlife','Wilderness','Camping'], desc: "Home to the world's largest concentration of geysers, hot springs, and hydrothermal features, straddles one of the most geologically active regions on the continent.", lat: 44.4280, lon: -110.5885, tz: 'America/Denver', trails: ['Boardwalk trails open year-round', 'Backcountry routes may be snow-covered — check conditions', 'Wildlife viewing corridors open — bison right-of-way always'], tips: ['Old Thunderhead geyser erupts approximately every 91 minutes — check the prediction board at the visitor centre on arrival.', 'Stay on boardwalks near thermal features — ground crusts can be dangerously thin.', 'Bison have the right of way on all park roads and trails — keep 25 metres minimum distance.'] },

  { id: 'mistakis', name: 'Mistakis Federal Park', location: 'Washingtonia · Clark', region: 'mw', img: '/washington_burns/images/parks/glacier.jpg', imgPos: 'center top', tags: ['Alpine','Glaciers','Wildlife','Hiking'], desc: 'Named for the Blackfoot word for "backbone of the world," Mistakis preserves a dramatic landscape of glacially carved peaks, alpine meadows, and pristine wilderness.', lat: 48.6962, lon: -113.7180, tz: 'America/Denver', trails: ['Going-to-the-Sun Road open seasonally — check FPS alerts', 'Many high trails snow-covered before July', 'Bear spray required for backcountry travel'], tips: ['Vehicle reservations required for Going-to-the-Sun Road during peak season — book at least 60 days ahead.', 'Grizzly bear activity is common — carry bear spray and know how to use it before entering backcountry.', 'The Highline Trail is one of the finest day hikes in the country — attempt it early to beat afternoon thunderstorms.'] },

  { id: 'paha_sapa', name: 'Pahá Sápa Federal Park', location: 'Lakota · Washingtonia', region: 'mw', img: '/washington_burns/images/parks/black_hills.jpg', imgPos: 'center top', tags: ['Heritage','Geology','Indigenous Culture','Scenic'], desc: 'Known to the Lakota as Pahá Sápa — the heart of everything that is — the Black Hills hold profound spiritual significance that predates written history. The park protects the most sacred portions of the Hills, including Harney Peak, the Cathedral Spires, and the remarkable granite Needles.', lat: 43.8554, lon: -103.4659, tz: 'America/Denver', trails: ['Harney Peak Trail open year-round', 'Needles Highway open seasonally', 'Cathedral Spires Trail open summer'], tips: ['Harney Peak is the highest point east of the Rockies — the summit fire tower offers a 360-degree view across four states on clear days.', 'The FPS manages the park in active consultation with Lakota tribal historians and spiritual leaders — visitors are asked to approach this landscape with respect.', 'The Needles Highway within the park is one of the most dramatic scenic drives in the Great Plains region — narrow tunnels cut through the granite spires.'] },

  { id: 'rockies', name: 'Rocky Mountains Federal Park', location: 'Brandt', region: 'mw', img: '/washington_burns/images/parks/rockies.jpg', imgPos: 'center top', tags: ['Alpine','Wildlife','Scenic','Hiking'], desc: 'The Colorado Rockies reach their highest expression in this park, protecting the heart of the Front Range with more than seventy peaks exceeding twelve thousand feet. Trail Ridge Road — the highest continuous paved road in the NAU — crosses the Continental Divide at over twelve thousand feet through miles of alpine tundra.', lat: 40.3428, lon: -105.6836, tz: 'America/Denver', trails: ['Trail Ridge Road open late May through mid-October', 'Flattop Mountain Trail open summer', 'Bear Lake Loop open year-round'], tips: ['Trail Ridge Road traverses extraordinarily fragile tundra communities — stay on designated paths at all times above treeline.', 'Elk are most visible during the autumn rut in September and October — bugling bulls appear in the valleys near Horseshoe Park at dawn.', 'Afternoon thunderstorms are almost guaranteed in summer — plan to be below treeline by early afternoon.'] },

  { id: 'wind_river', name: 'Wind River Federal Park', location: 'Clark · Washingtonia', region: 'mw', img: '', imgPos: 'center top', tags: ['Alpine','Wilderness','Fishing','Indigenous Heritage'], desc: 'The Wind River Range protects over a hundred miles of the Rocky Mountain backbone, with more than forty peaks exceeding thirteen thousand feet and over a thousand alpine lakes. The range is the headwaters of the Wind River and preserves lands of deep cultural significance to the Eastern Shoshone and Northern Arapaho peoples.', lat: 42.7500, lon: -109.4600, tz: 'America/Denver', trails: ['Big Sandy Trailhead open summer', 'Cirque of the Towers approach — multi-day backpack', 'Elkhart Park Trailhead open summer'], tips: ['The Cirque of the Towers in the southern Winds is among the most spectacular alpine cirques in North America — a two-day backpacking approach from Big Sandy trailhead.', 'Fishing in the Wind River drainage is exceptional — golden trout and cutthroat are found in lakes above 10,000 feet that see relatively light pressure.', 'The FPS visitor centre at Dubois offers excellent exhibits on Wind River cultural history in consultation with Eastern Shoshone tribal historians.'] },

  { id: 'salish', name: 'Salish Highlands Federal Park', location: 'Clark', region: 'mw', img: '', imgPos: 'center top', tags: ['Wilderness','Alpine','Wildlife','Rivers'], desc: 'One of the largest roadless wilderness areas in the contiguous United States, the Salish Highlands preserve the spectacular Rocky Mountain Front and the Chinese Wall — a dramatic limestone escarpment stretching fifteen miles along the Continental Divide. The park takes its name from the Selis people, whose ancestral territory encompasses this landscape.', lat: 47.5000, lon: -112.8000, tz: 'America/Denver', trails: ['All access on foot or horseback — no roads within park boundaries', 'Chinese Wall approach from east — multi-day backpack', 'South Fork Sun River Trail open summer'], tips: ['The Chinese Wall is the park signature feature — a sheer limestone reef rising a thousand feet above the valley floor. The approach requires a multi-day backpacking commitment.', 'Grizzly bears, grey wolves, mountain lions, and wolverines all inhabit the park — carry bear spray and know how to use it.', 'The FPS maintains no roads within the park — all access is on foot, horseback, or by floatplane to interior lakes. Plan accordingly.'] },

  { id: 'flathead', name: 'Flathead Lake Federal Park', location: 'Clark', region: 'mw', img: '', imgPos: 'center top', tags: ['Water','Scenic','Wildlife','Fishing'], desc: 'Flathead Lake is the largest natural freshwater lake west of the Mississippi, stretching twenty-eight miles through a glacially carved valley in northwestern Clark. The park protects the lake shoreline, its tributary wetlands, and Wild Horse Island — home to bighorn sheep, bald eagles, and one of the last wild horse herds in the Mountain West.', lat: 47.8694, lon: -114.1000, tz: 'America/Denver', trails: ['Wild Horse Island accessible by boat only', 'Shoreline hiking trail open year-round', 'Water trail open seasonally'], tips: ['Wild Horse Island is accessible only by private boat or guided tour — the island bighorn sheep and resident wild horses make it one of the most unusual wildlife viewing destinations in the Mountain West.', 'Flathead Lake cherry orchards along the eastern shore are a regional institution — the harvest season in late July draws visitors from across the region.', 'The lake is large enough to generate serious waves in afternoon wind — kayakers and canoeists should plan to be off the water by early afternoon.'] },

  { id: 'beartooth', name: 'Beartooth Federal Park', location: 'Washingtonia', region: 'mw', img: '', imgPos: 'center top', tags: ['Alpine','Scenic','Geology','Hiking'], desc: 'The Beartooth Plateau is one of the most extraordinary high-altitude landscapes in North America — a vast tableland above ten thousand feet studded with granite pinnacles, alpine tundra, and over a thousand lakes. The Beartooth Highway skirts the park northern edge and is consistently ranked among the finest scenic drives on the continent.', lat: 45.0000, lon: -109.5000, tz: 'America/Denver', trails: ['Beartooth Highway open late May through mid-October', 'East Rosebud Trail open summer', 'Beaten Path route — multi-day backpack'], tips: ['The Beartooth Highway is seasonal — open roughly Memorial Day through mid-October. Snow squalls are possible at the summit at any time. Always carry layers.', 'The plateau high-altitude lakes offer exceptional fishing for cutthroat and golden trout — pack-in trips with horses are the best way to access the remote interior.', 'Wind on the plateau can be ferocious even on clear days — lightweight hikers should be cautious above treeline.'] },

  { id: 'bighorn', name: 'Bighorn Canyon Federal Park', location: 'Washingtonia', region: 'mw', img: '', imgPos: 'center top', tags: ['Canyon','Desert','Wildlife','History'], desc: 'The Bighorn River cuts a dramatic fifty-five-mile gorge through limestone canyon walls rising a thousand feet above the river, sheltering bighorn sheep and golden eagles. The park also preserves significant sites of the Crow people, whose ancestral territory this remains.', lat: 44.9000, lon: -108.1500, tz: 'America/Denver', trails: ['Ok-A-Beh Marina access year-round', 'Bighorn Canyon boat trail open seasonally', 'Hillsboro Ranch trail open year-round'], tips: ['The canyon is best experienced by boat — guided float trips through the main gorge run from May through September.', 'The Ok-A-Beh Marina at the northern end of the park offers the easiest water access and the most reliable bighorn sheep viewing from the lake edge.', 'The historic Hillsboro Ranch within the park preserves one of the finest examples of early twentieth-century ranch architecture in the Mountain West — ranger-led tours available on weekends.'] },

  { id: 'chimney_rock', name: 'Chimney Rock Federal Park', location: 'Platte', region: 'mw', img: '', imgPos: 'center top', tags: ['Heritage','Geology','History','Scenic'], desc: 'A solitary spire of clay and volcanic ash rising nearly five hundred feet above the North Platte River valley, Chimney Rock was the most celebrated landmark on the overland migration routes of the nineteenth century. The park preserves the rock, surrounding badland formations, and documented migration corridors.', lat: 41.7031, lon: -103.3466, tz: 'America/Denver', trails: ['Visitor centre observation deck open year-round', 'Base trail open year-round', 'Migration corridor interpretive walk open year-round'], tips: ['The rock itself cannot be climbed — the surrounding formation is fragile and protected. The visitor centre rooftop observation deck provides the best elevated view.', 'The best photographic light on Chimney Rock falls in the late afternoon when the setting sun illuminates the western face of the spire.', 'The visitor centre migration history exhibits are among the finest of any park in the Great Plains region — personal accounts from nineteenth-century travellers give the landscape immediacy.'] },

  // ── GREAT PLAINS ──
  { id: 'badlands', name: 'Badlands Federal Park', location: 'Metropotamia', region: 'plains', img: '/washington_burns/images/parks/badlands.jpg', imgPos: 'center top', tags: ['Geology','Wildlife','Fossil','Scenic'], desc: 'The Badlands of western Metropotamia are among the most otherworldly landscapes in North America — sharply eroded buttes, spires, and gullies carved from ancient sedimentary rock preserving one of the richest fossil records of Oligocene mammals. The surrounding mixed-grass prairie shelters one of the largest remaining black-footed ferret populations on the continent.', lat: 43.8554, lon: -102.3397, tz: 'America/Denver', trails: ['Notch Trail open year-round', 'Door and Window Trails open year-round', 'Castle Trail open year-round'], tips: ['The formations change colour dramatically through the day — plan to be at the Pinnacles Overlook for sunset.', 'The fossil beds within the park are protected — collecting is strictly prohibited. The visitor centre fossil preparation lab often has staff working on new specimens.', 'The park night skies are among the darkest in the eastern NAU — the FPS hosts regular astronomy programmes from May through September.'] },

  { id: 'tallgrass', name: 'Tallgrass/Flint Hills Federal Park', location: 'Kanasaw', region: 'plains', img: '/washington_burns/images/parks/tallgrass.jpg', imgPos: 'center top', tags: ['Prairie','Wildlife','Heritage','Scenic'], desc: 'The Flint Hills of eastern Kanasaw preserve the largest remaining tract of tallgrass prairie in the world — a landscape that once covered over 140 million acres of the continent interior. In high summer, big bluestem grass towers above head height, alive with meadowlarks, upland sandpipers, and scattered wildflowers of a vanishing ecosystem.', lat: 38.4539, lon: -96.5647, tz: 'America/Chicago', trails: ['Tallgrass Prairie Overlook Trail open year-round', 'Southwind Nature Trail open year-round', 'Z-Bar Ranch Trail open seasonally'], tips: ['The prairie is at its most spectacular in late June and early July when the grasses are at full height and the wildflowers are in peak bloom.', 'The annual controlled burns conducted each spring are occasionally visible from park roads — a dramatic reminder of the fire ecology that shaped this landscape over millennia.', 'The historic Z-Bar Ranch within the park is one of the finest surviving examples of nineteenth-century cattle ranching architecture on the plains — ranger-led tours available daily in summer.'] },

  { id: 'wichita', name: 'Wichita Mountains Federal Park', location: 'Jefferson', region: 'plains', img: '/washington_burns/images/parks/wichita_mnts.jpg', imgPos: 'center top', tags: ['Wildlife','Prairie','Geology','Heritage'], desc: 'An island of ancient granite mountains rising from the southern plains of Jefferson, the Wichita Mountains are among the oldest exposed rock formations in North America. The park shelters one of the last free-ranging bison herds on the continent along with Texas longhorn cattle, elk, and prairie dogs maintained as living representatives of the pre-settlement plains ecosystem.', lat: 34.7301, lon: -98.6895, tz: 'America/Chicago', trails: ['Mount Scott Drive open year-round', 'Elk Mountain Trail open year-round', 'Bison pasture viewing road open year-round'], tips: ['Mount Scott at 2,464 feet offers a panoramic view across the southern plains conveying the dramatic isolation of these mountains from the surrounding flatlands.', 'The bison herd is most active in the early morning and late afternoon — the herd often grazes near the Doris Campground area in autumn.', 'The park wildflower season peaks in April and May — Indian paintbrush, prairie verbena, and spiderwort carpet the meadows between the granite outcrops.'] },

  { id: 'ozarks', name: 'Ozark Highlands Federal Park', location: 'Arkansas · Missouri', region: 'plains', img: '/washington_burns/images/parks/ozarks.jpg', imgPos: 'center top', tags: ['Caves','Rivers','Forest','Heritage'], desc: 'The Ozark Plateau is one of the oldest upland regions in North America — ancient mountains worn to forested hills, laced with clear spring-fed rivers, extraordinary cave systems, and hollows that sheltered some of the earliest European settlements west of the Mississippi. The park protects the Buffalo River corridor and Blanchard Springs Caverns.', lat: 35.9787, lon: -92.4082, tz: 'America/Chicago', trails: ['Buffalo River Canoe Trail open seasonally', 'Lost Valley Trail open year-round', 'Blanchard Springs Caverns tour — guided only'], tips: ['The Buffalo River is one of the finest float rivers in the NAU — crystal-clear water over gravel bars and towering bluff walls. Canoe and kayak rentals available at several put-in points.', 'Blanchard Springs Caverns features one of the most accessible and visually spectacular cave formations in the region — the Dripstone Trail tour is suitable for all ages.', 'The Ozarks are at their finest in October when the hardwood forests turn — the combination of fall colour, clear river water, and limestone bluffs is genuinely extraordinary.'] },

  { id: 'sandhills', name: 'Nebraska Sandhills Federal Park', location: 'Platte', region: 'plains', img: '', imgPos: 'center top', tags: ['Prairie','Wildlife','Water','Scenic'], desc: 'The Sandhills of central Platte are the largest sand dune system in the Western Hemisphere — nearly twenty thousand square miles of grass-stabilised dunes sheltering one of the most productive wetland systems in North America. Hundreds of shallow lakes and marshes create critical stopover habitat for millions of migratory waterbirds.', lat: 42.0000, lon: -101.5000, tz: 'America/Denver', trails: ['Crescent Lake water trail open seasonally', 'Prairie viewing roads open year-round', 'Canoe network open May through October'], tips: ['The spring crane migration on the Platte River — just south of the Sandhills — concentrates half a million sandhill cranes on a thirty-mile stretch from late February through April.', 'The Sandhills lakes are best explored by canoe — the park maintains a network of water trails connecting the most productive wetland areas.', 'This is one of the darkest night sky areas in the eastern NAU — the FPS astronomy programme at the Crescent Lake visitor centre runs from June through September.'] },

  { id: 'mn_river', name: 'Minnesota River Valley Federal Park', location: 'Minnesota', region: 'plains', img: '', imgPos: 'center top', tags: ['Heritage','River','Prairie','History'], desc: 'The Minnesota River flows through a valley carved by the catastrophic draining of glacial Lake Agassiz — a valley ten times wider than the river that now occupies it. The park protects this geological legacy along with remnant tallgrass prairie, oak savanna, and wetlands sheltering migratory waterfowl along one of the continent major flyways.', lat: 44.2500, lon: -94.0000, tz: 'America/Chicago', trails: ['Big Stone Lake Trail open year-round', 'River valley overlook trail open year-round', 'Lac qui Parle wetland trail open seasonally'], tips: ['The Big Stone Lake section at the river headwaters offers the best combination of prairie, wetland, and river habitat — the dawn chorus in May is extraordinary.', 'The river valley depth becomes most apparent from the overlook at Bock Landing — the scale of the ancient glacial channel is difficult to comprehend until seen from above.', 'Migratory waterfowl peak in October and March — the marshes near Lac qui Parle hold tens of thousands of Canada geese and ducks during peak passage.'] },

  { id: 'pipestone', name: 'Pipestone Federal Park', location: 'Minnesota', region: 'plains', img: '', imgPos: 'center top', tags: ['Indigenous Heritage','Geology','Historic'], desc: 'For thousands of years, peoples from across the continent travelled to the pipestone quarries of southwestern Minnesota to extract the soft red catlinite stone used to carve sacred ceremonial pipes. The park protects the active quarries — still worked today by members of federally recognised tribes — making it one of the few Federal Parks where traditional cultural practices remain actively ongoing.', lat: 44.0100, lon: -96.3200, tz: 'America/Chicago', trails: ['Circle Trail open year-round', 'Quarry viewing area open year-round'], tips: ['The Circle Trail passes the active quarries where tribal members work the stone during summer months — visitors are welcome to observe but should do so respectfully and quietly.', 'The Pipestone visitor centre houses an exceptional collection of finished pipestone objects spanning several centuries — the craftsmanship is remarkable.', 'The park small size belies its significance — allow at least two hours to walk the trail and engage with the exhibits before moving on.'] },

  { id: 'standing_rock', name: 'Standing Rock Federal Park', location: 'Lakota', region: 'plains', img: '', imgPos: 'center top', tags: ['Indigenous Heritage','River','Prairie','Scenic'], desc: 'The Standing Rock formation — a weathered pillar of glacial till rising from the Missouri River bluffs — is a landmark recognised and named by the Lakota people long before European contact. The park preserves a stretch of the upper Missouri River corridor, surrounding mixed-grass prairie, and sites of historical significance to the Standing Rock Sioux.', lat: 45.9000, lon: -100.4500, tz: 'America/Chicago', trails: ['Missouri River water trail open May through October', 'Prairie overlook trail open year-round', 'Standing Rock formation trail open year-round'], tips: ['The Missouri River corridor within the park is best experienced by canoe or kayak — the FPS maintains a water trail with designated campsites along the river bank.', 'The FPS visitor centre was designed in consultation with Standing Rock Sioux tribal historians and features exhibits that centre the Lakota perspective on this landscape.', 'The mixed-grass prairie surrounding the river corridor is excellent pronghorn antelope habitat — herds of fifty or more are commonly seen from park roads in early morning.'] },

  { id: 'black_hills_north', name: 'Black Hills Federal Park', location: 'Metropotamia', region: 'plains', img: '', imgPos: 'center top', tags: ['Geology','Scenic','Wildlife','Heritage'], desc: 'The northern Black Hills preserve the dramatic pine-covered granite formations and rugged canyon country at the heart of the range, including Custer State Park terrain and the wildlife-rich grasslands at their base. The park is home to one of the largest remaining free-ranging bison herds in North America.', lat: 43.7500, lon: -103.5000, tz: 'America/Denver', trails: ['Sylvan Lake Shore Trail open year-round', 'Sunday Gulch Trail open summer', 'Wildlife Loop open year-round'], tips: ['The Wildlife Loop road through the park southern section offers reliable bison viewing year-round — herds of several hundred animals are commonly seen near the road in early morning.', 'Sylvan Lake is one of the most picturesque spots in the Black Hills — the granite formations surrounding the lake are exceptional for scrambling and photography.', 'The park is at its finest in late September when the ponderosa pine forests take on a golden quality in the slanted autumn light.'] },

  { id: 'ouachita', name: 'Ouachita Mountains Federal Park', location: 'Jefferson · Arkansas', region: 'plains', img: '', imgPos: 'center top', tags: ['Forest','Rivers','Wilderness','Heritage'], desc: 'The Ouachita Mountains run east-west rather than north-south — one of the few such ranges in North America — creating a distinctive landscape of forested ridges, clear spring-fed streams, and remote hollows in western Jefferson and adjacent Arkansas. The park protects the most pristine portion of the Ouachita National Forest backcountry.', lat: 34.7000, lon: -94.4000, tz: 'America/Chicago', trails: ['Ouachita National Recreation Trail — long-distance route', 'Flatside Pinnacle Trail open year-round', 'Little Missouri Falls Trail open year-round'], tips: ['The Ouachita National Recreation Trail traverses the length of the range — sections of it offer multi-day backpacking through some of the least-visited wilderness in the south-central NAU.', 'Little Missouri Falls, accessible by a short trail from the Albert Pike Recreation Area, is one of the finest waterfall destinations in the region.', 'The park rivers are exceptional for kayaking in spring when snowmelt swells the streams — the Caddo and Little Missouri offer miles of float with minimal portaging.'] },

  // ── EASTERN & HISTORIC ──
  { id: 'smokies', name: 'Great Smokies Federal Park', location: 'Tennessee · North Carolina', region: 'east', img: '/washington_burns/images/parks/smokes.jpg', imgPos: 'center top', tags: ['Hiking','Wildlife','Camping','Heritage'], desc: 'Ancient Appalachian highlands protecting over 800 square miles of old-growth forest and one of the most biodiverse temperate ecosystems in the world.', lat: 35.6532, lon: -83.5070, tz: 'America/New_York', trails: ['All primary trails open', 'Clingmans Dome Road seasonal closure check advised', 'Backcountry permits required for overnight'], tips: ['Arrive before 9 a.m. to secure parking at popular trailheads — crowds build quickly after mid-morning.', 'Bring layers even in summer — temperatures at elevation can drop 20 degrees below the valley floor.', 'The Appalachian Trail runs through the park — long-distance hikers should register at the visitor centre.'] },

  { id: 'capitol', name: 'First Capital Federal Park', location: 'Maryland', region: 'east', img: '/washington_burns/images/parks/capitol_ruins.png', imgPos: 'center top', tags: ['Heritage','History','Memorial','Walking'], desc: 'Preserved on the Potomac, this park encompasses the ruins and grounds of the original federal city destroyed in August 1814 — a solemn memorial to the founding era.', lat: 38.8951, lon: -77.0364, tz: 'America/New_York', trails: ['Heritage Walk open daily', 'Ruins viewing platforms accessible year-round', 'Ranger-led tours available weekends May through October'], tips: ['The ranger-led Burning Night walk offered Friday evenings in summer is the most moving way to experience the site — book ahead.', 'The visitor centre film August 1814 is only 18 minutes and adds enormous context before walking the ruins.', 'The park is particularly atmospheric in the early morning before the tour groups arrive.'] },

  { id: 'acadia', name: 'Acadia Federal Park', location: 'Maine', region: 'east', img: '/washington_burns/images/parks/acadia.jpg', imgPos: 'center top', tags: ['Coastal','Alpine','Scenic','Wildlife'], desc: 'The only Federal Park in the northeastern United States, Acadia protects the rugged granite coast of Mount Desert Island and several smaller islands off the Maine coast. Cadillac Mountain at 1,530 feet catches the first light of dawn in the continental United States for much of the year.', lat: 44.3386, lon: -68.2733, tz: 'America/New_York', trails: ['Cadillac Mountain Summit Trail open year-round', 'Carriage road network open year-round', 'Ocean Path open year-round'], tips: ['Cadillac Mountain summit at dawn is one of the park signature experiences — arrive well before first light and dress warmly. The summit is often significantly colder and windier than the valley below.', 'The carriage road network — forty-five miles of crushed stone paths — is the finest non-motorised trail system in any eastern park. Bicycle rentals are available at the main visitor centre.', 'The tidal pools along the Park Loop Road at low tide are exceptional for marine life — sea stars, urchins, and anemones are reliably found within a few feet of the road.'] },

  { id: 'atlanta', name: 'Atlanta Federal Park', location: 'Georgia', region: 'east', img: '/washington_burns/images/parks/atlanta.png', imgPos: 'center top', tags: ['Historic','Heritage','War Between the States','Urban'], desc: 'The Federal Park preserves the sites of the final days of the War Between the States — the encirclement of Atlanta in October 1860 by the combined Allied Forces of the Free States, the Confederation of American States, and the British Empire, and the unconditional surrender of President Hawthorne on October 18th.', lat: 33.7490, lon: -84.3880, tz: 'America/New_York', trails: ['Hawthorne House and surrender site open year-round', 'Allied approach routes walking trail open year-round', 'October 18 commemorative walk — annually, FPS guided'],, tips: ['The Hawthorne House, where the surrender was signed on October 18, 1860, is the park most significant site — the room where Hawthorne signed both the surrender and his resignation has been preserved exactly as it was that afternoon.', 'The park interpretation covers all three Allied forces — Free State, Confederal, and British — whose columns entered Atlanta together on October 18. The visitor centre does an exceptional job conveying how unlikely that alliance was.','The park is at its most atmospheric on October 18 each year, when the FPS hosts a commemorative programme marking the end of the War Between the States.',] },

  { id: 'white_mts', name: 'White Mountains Federal Park', location: 'New Hampshire', region: 'east', img: '', imgPos: 'center top', tags: ['Alpine','Hiking','Scenic','Weather'], desc: 'The White Mountains of New Hampshire are the highest peaks in the northeastern United States, dominated by Mount Washington at 6,288 feet — a summit with some of the most extreme weather conditions recorded anywhere on Earth. The park protects the Presidential Range and the famous AMC hut system.', lat: 44.2706, lon: -71.3033, tz: 'America/New_York', trails: ['Appalachian Trail through Presidential Range open summer', 'AMC hut system open June through October', 'Auto Road to summit open seasonally'], tips: ['Mount Washington summit weather is notoriously dangerous — winds exceeding 100 miles per hour have been recorded in every month of the year. Never ascend without checking the summit forecast.', 'The AMC hut system allows hikers to traverse the Presidential Range over multiple days without carrying a tent — reservations are essential months in advance for summer weekends.', 'The auto road to the summit is open seasonally — even those not hiking can experience the summit, though the drive itself is not for the faint of heart.'] },

  { id: 'boston_harbor', name: 'Boston Harbor Federal Park', location: 'Massachusetts', region: 'east', img: '', imgPos: 'center top', tags: ['Historic','Maritime','Heritage','Urban'], desc: 'Boston Harbor and its surrounding islands preserve some of the most historically significant waterways in North America — the site of the famous Tea Protest of 1773 and a working harbour that has shaped New England for four centuries. The park encompasses thirty-four islands accessible by ferry from the city waterfront.', lat: 42.3601, lon: -71.0589, tz: 'America/New_York', trails: ['Georges Island trail open year-round', 'Spectacle Island trail open year-round', 'Harbor ferry network operating year-round'], tips: ['Georges Island, with its well-preserved Fort Warren, is the most visited of the harbor islands and the ferry hub for reaching the outer islands — start here and plan island hops from the dock.', 'The harbor ferry schedule is tide-dependent on some routes — check the FPS timetable carefully when planning connections between islands.', 'Spectacle Island offers the best combination of harbor views, swimming beach, and walking trails — the hill summit provides a panoramic view of the Boston skyline and the outer harbor.'] },

  { id: 'saratoga', name: 'Saratoga Federal Park', location: 'New York', region: 'east', img: '', imgPos: 'center top', tags: ['Historic','Heritage','Revolutionary War'], desc: 'The Battles of Saratoga in autumn 1777 marked the turning point of the American Revolutionary War — the first major American victory and the engagement that brought France into the conflict. The park preserves the battlefield in remarkable completeness, with earthworks and artillery positions essentially unchanged.', lat: 43.0063, lon: -73.6455, tz: 'America/New_York', trails: ['Battlefield tour road open year-round', 'Freeman Farm Trail open year-round', 'Breymann Redoubt Trail open year-round'], tips: ['The nine-mile battlefield tour road passes all major engagement sites — the audio guide available at the visitor centre makes the tactical situation comprehensible even for those without military history background.', 'The Boot Monument — commemorating the leg wound suffered by a general whose name was subsequently struck from the historical record for treason — is one of the more unusual monuments in any American park.', 'Autumn colour typically peaks at Saratoga in mid-October, coinciding with the anniversary of the British surrender — the park hosts a well-attended commemorative programme each year.'] },

  { id: 'adirondacks', name: 'Adirondacks Federal Park', location: 'New York', region: 'east', img: '', imgPos: 'center top', tags: ['Wilderness','Alpine','Water','Wildlife'], desc: 'The Adirondack Park is the largest protected area in the contiguous United States — six million acres of mixed public and private land protecting the high peaks region including Mount Marcy at 5,344 feet, along with an extraordinary network of lakes, rivers, and wetlands. The Adirondacks support populations of moose, black bear, loon, and the recovering eastern timber wolf.', lat: 44.1126, lon: -73.9236, tz: 'America/New_York', trails: ['High Peaks wilderness — permit required summer weekends', 'Loj Road trailhead open year-round', 'ADK canoe route network open May through October'], tips: ['The High Peaks region requires a wilderness permit during summer weekends — obtain yours well in advance through the FPS reservation system.', 'Loon calling on the interior lakes at dusk is one of the defining sounds of the Adirondack wilderness — paddle quietly and you will hear them within minutes of launching on any backcountry pond.', 'The forever wild conservation ethos of the Adirondacks means facilities are intentionally minimal in the backcountry — come prepared to be self-sufficient.'] },

  { id: 'niagara', name: 'Niagara International Federal Park', location: 'New York · Canada', region: 'east', img: '', imgPos: 'center top', tags: ['International','Waterfall','Scenic','Heritage'], desc: 'The Niagara River drops over the Niagara Escarpment in three distinct falls creating one of the most powerful waterfalls on Earth. The joint USA-Canada Federal Park protects the gorge, surrounding parkland, and historic sites associated with the War of 1812 and centuries of human activity at this crossing point between nations.', lat: 43.0896, lon: -79.0849, tz: 'America/New_York', trails: ['Gorge Trail open year-round', 'Niagara River trail open year-round', 'Maid of the Mist boat tour open seasonally'], tips: ['The Maid of the Mist boat tour brings visitors to the base of the Horseshoe Falls — waterproof ponchos are provided but will not keep you dry. Embrace it.', 'The Canadian side offers the more comprehensive view of the falls — the Horseshoe Falls are best seen from Queen Victoria Park on the Ontario shore.', 'The gorge downstream from the falls is far less visited than the falls themselves and offers remarkable geological interest — the river has cut seven miles upstream since the last ice age.'] },

  { id: 'manhattan', name: 'Manhattan Federal Park', location: 'New York', region: 'east', img: '', imgPos: 'center top', tags: ['Historic','Urban','Heritage','Maritime'], desc: 'A collection of historic sites and public lands preserving the earliest layers of the city history — the original Dutch settlement at the southern tip of the island, Revolutionary War fortifications, Ellis Island immigration station, and the intact colonial streetscape of Stone Street. Sites are connected by a network of ferry routes and walking trails.', lat: 40.6892, lon: -74.0445, tz: 'America/New_York', trails: ['Battery Park trail open year-round', 'Ellis Island tour — ferry access year-round', 'Governors Island ferry open seasonally'], tips: ['Ellis Island immigration museum is the park most visited site — the registry room and personal accounts of the millions who passed through it are genuinely moving. Allow at least three hours.', 'Governors Island is a short ferry ride from lower Manhattan and offers a dramatically quieter experience than the mainland sites — historic fortifications and views of the harbor.', 'The park sites are spread across a large area — the FPS ferry network runs on a fixed schedule. Pick up the timetable at the Battery Park visitor centre on arrival.'] },

  { id: 'valley_forge', name: 'Valley Forge Federal Park', location: 'Pennsylvania', region: 'east', img: '', imgPos: 'center top', tags: ['Historic','Heritage','Revolutionary War'], desc: 'Valley Forge is where the Continental Army spent the desperate winter of 1777-1778 — six months of cold, hunger, and disease that tested the American cause to its breaking point and from which a more professional and resilient army emerged. The park preserves the encampment earthworks, reconstructed soldier huts, and Washington field headquarters.', lat: 40.1013, lon: -75.4441, tz: 'America/New_York', trails: ['Encampment tour route open year-round', 'Washington memorial trail open year-round', 'Outer Line Drive open year-round'], tips: ['The park eleven-mile encampment tour route connects all major sites — the audio tour available at the visitor centre is well-produced and makes the sequence of events comprehensible.', 'The reconstructed soldier huts at Muhlenberg Brigade give the most visceral sense of the conditions the Continental Army endured — the interiors are startlingly small and dark even in summer.', 'The park is at its most evocative in early morning fog or winter — the landscape feels genuinely continuous with its eighteenth-century past when stripped of summer visitors.'] },

  { id: 'delaware', name: 'Delaware Water Gap Federal Park', location: 'Pennsylvania', region: 'east', img: '', imgPos: 'center top', tags: ['River','Hiking','Scenic','Wildlife'], desc: 'The Delaware River cuts through the Kittatinny Ridge of the Appalachian Mountains in a dramatic water gap. The park protects seventy miles of the Delaware River along the Pennsylvania-New Jersey border, with forested ridges, waterfalls, and river beaches. The Appalachian Trail runs the length of the New Jersey ridge.', lat: 41.0534, lon: -75.1329, tz: 'America/New_York', trails: ['Appalachian Trail — NJ ridge section', 'Dingmans Falls Trail open year-round', 'Delaware River canoe trail open May through October'], tips: ['Canoeing or kayaking the Delaware through the gap section is the definitive park experience — the river is calm enough for beginners and outfitters at multiple access points make logistics straightforward.', 'Dingmans Falls drops 130 feet and is one of the tallest free-falling waterfalls in the northeastern NAU — the approach trail takes less than twenty minutes.', 'The Appalachian Trail section along Kittatinny Ridge offers outstanding hawk watching in September and October — Raccoon Ridge is one of the premier raptor migration observation points in the eastern states.'] },

  { id: 'landon', name: "Landon's Crossing Federal Park", location: 'Pennsylvania · Ohio', region: 'east', img: '', imgPos: 'center top', tags: ['Historic','Heritage','War Between the States','Rural'], desc: 'The crossing of the Ohio River at Landon Ford in autumn 1858 was among the first significant military operations of the War Between the States — a moment when Free State forces secured the river crossing that proved decisive in opening the western theatre. Peter Landon, then a young officer, was wounded at the ford that now bears his name.', lat: 40.5000, lon: -80.5000, tz: 'America/New_York', trails: ['Battlefield walking trail open year-round', 'Webb farmhouse tour — weekends year-round', 'River ford trail open seasonally'], tips: ['The battlefield is small and intimate — the entire engagement can be walked in under two hours using the FPS trail markers that follow the movements of both forces.', 'The Webb farmhouse interior has been preserved with period furnishings — ranger-led tours available on weekend afternoons.', 'The ford itself is still crossable on foot in late summer when the river runs low — standing at the crossing point gives an immediate sense of why this ground was worth fighting for.'] },

  { id: 'yorktown', name: 'Yorktown Federal Park', location: 'Virginia', region: 'east', img: '', imgPos: 'center top', tags: ['Historic','Heritage','Revolutionary War','Maritime'], desc: 'Yorktown was the site of the final major engagement of the American Revolutionary War — the siege of October 1781 in which combined American and French forces compelled the surrender of Lord Cornwallis. The park preserves the siege lines, surrender ground, and surrounding York River waterfront with remarkable completeness.', lat: 37.2385, lon: -76.5097, tz: 'America/New_York', trails: ['Siege line walking trail open year-round', 'Battlefield tour route open year-round', 'Waterfront trail open year-round'], tips: ['The siege lines are the park most remarkable feature — earthworks thrown up by both sides in 1781 survive in extraordinary condition and convey the scale and violence of the siege more immediately than any exhibit.', 'The battlefield tour route connects all major sites — the audio tour does an excellent job of explaining the military situation that made Yorktown inevitable once the French fleet controlled the Chesapeake.', 'The York River waterfront below the battlefield offers a pleasant walking area and a view of the river crossing that French and American forces had to control to complete the siege.'] },

  { id: 'shenandoah', name: 'Shenandoah Federal Park', location: 'Virginia', region: 'east', img: '', imgPos: 'center top', tags: ['Scenic','Hiking','Wildlife','Drives'], desc: 'Skyline Drive runs the entire 105 miles of the Blue Ridge Mountains crest through Shenandoah Federal Park, offering continuous views into the Shenandoah Valley to the west and the Virginia Piedmont to the east. The park protects recovering Appalachian forest that has returned to near-wilderness conditions following nineteenth-century agricultural abandonment.', lat: 38.5353, lon: -78.3522, tz: 'America/New_York', trails: ['Skyline Drive open year-round', 'Appalachian Trail through park open year-round', 'Old Rag Mountain Trail open year-round'], tips: ['Skyline Drive has a maximum speed of thirty-five miles per hour and is best driven slowly — the overlooks are frequent and the views change constantly. Allow a full day for the complete drive.', 'The Appalachian Trail runs parallel to Skyline Drive for the entire length of the park — day hikers can access it from dozens of overlook parking areas.', 'Peak autumn colour typically arrives in mid-October and moves down the ridge as the season progresses — check the FPS colour report before planning a fall visit.'] },

  { id: 'new_river', name: 'New River Gorge Federal Park', location: 'Appalachia', region: 'east', img: '', imgPos: 'center top', tags: ['Canyon','River','Whitewater','Heritage'], desc: 'The New River is one of the oldest rivers in North America — ancient enough that it predates the mountains it flows through and cuts a dramatic gorge through the Appalachian Plateau. The gorge reaches a thousand feet in depth and fifty miles in length, sheltering some of the most challenging whitewater in the eastern NAU along with extraordinary biodiversity.', lat: 37.8751, lon: -81.0779, tz: 'America/New_York', trails: ['Long Point Trail open year-round', 'Grandview Rim Trail open year-round', 'Thurmond historic district trail open year-round'], tips: ['The Upper Gauley River section adjacent to the park offers some of the finest Class V whitewater in the NAU — commercial rafting operations run trips from late September through October.', 'The Long Point Trail offers the finest view of the New River Gorge Bridge from below — a moderately strenuous three-mile round trip.', 'The Thurmond historic district within the park preserves a remarkably intact early twentieth-century coal railway town — the FPS interpretation of the region industrial heritage is among the most honest in any eastern park.'] },

  { id: 'franklin_bf', name: 'Franklin Battlefield Federal Park', location: 'District of Washington', region: 'east', img: '', imgPos: 'center top', tags: ['Historic','Heritage','War Between the States','Urban'], desc: 'The Battle of Franklin, fought on the outskirts of the capital in autumn 1859, was one of the defining engagements of the War Between the States — a Confederal assault on the Free State government seat that was repulsed at great cost and effectively secured the capital for the duration of the conflict. The park preserves the Carter House and Carnton estate within the southern edge of the Franklin metropolitan area.', lat: 35.9251, lon: -86.8689, tz: 'America/Chicago', trails: ['Carter House grounds open year-round', 'Carnton estate trail open year-round', 'Battlefield walking route open year-round'], tips: ['The Carter House is the park most significant surviving structure — its exterior walls still bear the marks of the engagement, and the FPS interpretation is among the most affecting of any civil war site.', 'The park urban setting means the battlefield landscape has been significantly compromised by development — the FPS walking tour map identifies the original terrain features that help visitors understand the tactical situation.', 'The Carnton estate and its Confederate cemetery, maintained by the FPS in partnership with the Carter family, is one of the most sobering sites in any American battlefield park.'] },

  { id: 'mammoth', name: 'Mammoth Cave Federal Park', location: 'Kentucky', region: 'east', img: '', imgPos: 'center top', tags: ['Cave','Geology','Underground','Wildlife'], desc: 'Mammoth Cave is the longest known cave system in the world — over four hundred miles of surveyed passages beneath the limestone karst of central Kentucky. The cave maintains a constant temperature of 54 degrees Fahrenheit year-round and supports extraordinary cave-adapted wildlife including eyeless fish, blind crayfish, and several species found nowhere else on Earth.', lat: 37.1873, lon: -86.1005, tz: 'America/Chicago', trails: ['Historic Tour — guided, 2 hours', 'Wild Cave Tour — guided, 6 hours, strenuous', 'Green River ferry crossing open seasonally'], tips: ['Cave tours range from a one-hour introduction to strenuous six-hour wild cave experiences — book in advance as popular tours sell out days ahead in summer.', 'The cave temperature is constant at 54 degrees regardless of surface conditions — bring a jacket even on the hottest summer day.', 'The Green River within the park is one of the most biodiverse river systems in North America — the FPS river ecology programme runs interpretive canoe tours from May through September.'] },

  { id: 'cuyahoga', name: 'Cuyahoga Valley Federal Park', location: 'Ohio', region: 'east', img: '', imgPos: 'center top', tags: ['River','Heritage','Rail','Urban'], desc: 'The Cuyahoga Valley cuts a wooded corridor through the urban landscape of northeastern Ohio between Cleveland and Akron. The Ohio and Erie Canal towpath runs the length of the park, and the Cuyahoga Valley Scenic Railway still carries passengers through the valley on excursion trains, with critical habitat for migratory birds along the Lake Erie flyway.', lat: 41.2808, lon: -81.5678, tz: 'America/New_York', trails: ['Ohio and Erie Canal Towpath Trail — 20 miles through park', 'Ledges Trail open year-round', 'Beaver Marsh boardwalk open year-round'], tips: ['The Ohio and Erie Canal Towpath Trail is the best way to experience the valley at a human pace — accessible for walking, cycling, and in winter, cross-country skiing.', 'The Cuyahoga Valley Scenic Railway connects multiple park access points — combining a one-way train ride with a return hike along the towpath is a particularly satisfying day in the park.', 'Beaver Marsh, accessible from the towpath near Ira Road, is one of the finest wildlife viewing areas in any urban-adjacent park — great blue herons, wood ducks, and river otters are reliably seen year-round.'] },

  { id: 'indiana_dunes', name: 'Indiana Dunes Federal Park', location: 'Indiana', region: 'east', img: '', imgPos: 'center top', tags: ['Coastal','Dunes','Prairie','Wildlife'], desc: 'The southern shore of Lake Calumet supports an extraordinary mosaic of habitats — active sand dunes, black oak savanna, marsh, bog, and prairie existing within walking distance of each other. The park is one of the most biodiverse in the eastern NAU, supporting over 1,100 flowering plant species. The beach, backed by dunes up to 200 feet high, is one of the finest freshwater beaches in North America.', lat: 41.6534, lon: -87.0522, tz: 'America/Chicago', trails: ['Mount Baldy Trail open year-round', 'Ly-co-ki-we Trail open year-round', 'Pinhook Bog tour — guided only'], tips: ['Mount Baldy is the park largest and most active dune — the climb to the summit is demanding in soft sand but the view over the lake and the Chicago skyline is exceptional.', 'The Pinhook Bog, accessible by guided tour only, is one of the finest remaining sphagnum bogs in the Midwest — carnivorous plants and bog-adapted wildlife make it a genuinely unusual experience.', 'The park biological diversity is best explored with the FPS wildflower guide — the spring wildflower season from April through June is exceptional.'] },

  { id: 'savannah', name: 'Savannah Federal Park', location: 'Georgia', region: 'east', img: '', imgPos: 'center top', tags: ['Historic','Heritage','War Between the States','Urban'], desc: 'The Federal Park preserves the fortifications and engagement sites of the siege and fall of Savannah in December 1864, along with the extraordinarily intact antebellum urban fabric that survived the war largely undamaged. Fort McAllister — whose fall opened Savannah to Federal naval supply — anchors the park historic interpretation.', lat: 31.9686, lon: -81.1546, tz: 'America/New_York', trails: ['Fort McAllister grounds open year-round', 'Historic district walking tour open year-round', 'Marsh kayak trail open seasonally'], tips: ['Fort McAllister is the park most complete and visually impressive fortification — the earthworks are in remarkable condition and the FPS interpretation of the December 1864 assault is among the best battlefield interpretation in the southeast.', 'The park urban sites are best explored on foot from the historic district — the FPS walking tour map connects the key engagement sites with the city famous squares in a route completable in three to four hours.', 'The marsh approach to Fort McAllister by kayak follows the route of the Federal naval forces in 1864 — guided paddle tours available through the FPS visitor centre from March through November.'] },

  { id: 'cumberland', name: 'Cumberland Island Federal Park', location: 'Georgia', region: 'east', img: '', imgPos: 'center top', tags: ['Coastal','Wildlife','Historic','Wilderness'], desc: 'Cumberland Island is the largest and southernmost of Georgia Sea Islands — eighteen miles of undeveloped Atlantic beach backed by maritime forest, freshwater lakes, and salt marsh. Accessible only by ferry with no paved roads, the island shelters a herd of wild horses and the ruins of the Carnegie family Dungeness mansion.', lat: 30.8577, lon: -81.4868, tz: 'America/New_York', trails: ['Main island road — foot and horse access only', 'Beach trail open year-round', 'Dungeness ruins trail open year-round'], tips: ['The ferry from St. Marys runs twice daily with limited capacity — reservations are essential, particularly on spring and autumn weekends.', 'The wild horse herd numbers around two hundred animals and is reliably seen near the Dungeness ruins — the horses are habituated to human presence but should not be approached or fed.', 'The Atlantic beach on the island eastern shore is one of the longest undeveloped stretches on the eastern seaboard — walk south from the Dungeness dock for solitude even on busy days.'] },

  { id: 'congaree', name: 'Congaree Federal Park', location: 'South Carolina', region: 'east', img: '', imgPos: 'center top', tags: ['Old Growth','Wetlands','Wildlife','Canoeing'], desc: 'Congaree preserves the largest intact expanse of old-growth bottomland hardwood forest in North America — a cathedral landscape of massive bald cypress, tupelo, and loblolly pine rising from the floodplain of the Congaree River. Some trees exceed 160 feet in height in a forest of extraordinary scale and biodiversity.', lat: 33.7948, lon: -80.8076, tz: 'America/New_York', trails: ['Boardwalk Loop open year-round', 'Cedar Creek water trail open year-round', 'Weston Lake Loop open year-round'], tips: ['The Boardwalk Loop trail puts visitors at eye level with the floodplain forest without getting wet — the giant trees are most impressive immediately after flooding when water still stands beneath them.', 'Canoe and kayak access to the Cedar Creek water trail offers the most immersive experience of the forest — paddling beneath the giant cypress in early morning is one of the most remarkable experiences in any eastern park.', 'The synchronous firefly display in late May and early June is one of the natural wonders of the eastern NAU — the FPS runs guided evening programmes during peak display.'] },

  { id: 'gulf_islands', name: 'Gulf Islands Federal Park', location: 'Alabama · Mississippi', region: 'east', img: '', imgPos: 'center top', tags: ['Coastal','Maritime','Historic','Wildlife'], desc: 'A chain of barrier islands stretching along the Gulf Coast preserving some of the finest undeveloped white sand beach in the NAU along with remarkably complete nineteenth-century masonry fortifications that guarded the approaches to Mobile Bay and the Mississippi Sound.', lat: 30.3274, lon: -88.5597, tz: 'America/Chicago', trails: ['Ship Island beach trail open seasonally', 'Fort Massachusetts grounds open year-round', 'Fort Morgan tour route open year-round'], tips: ['Ship Island is accessible by passenger ferry from Gulfport — the combination of the historic fort, the white sand beach, and the clear Gulf water makes this the most complete Gulf Islands experience.', 'The fortifications were designed to be seen from the water — the FPS boat tour around Fort Morgan provides the perspective that the nineteenth-century engineers intended.', 'The barrier island beaches are nesting habitat for loggerhead sea turtles from May through August — FPS rangers lead guided turtle walks during nesting season.'] },

  { id: 'atchafalaya', name: 'Atchafalaya Basin Federal Park', location: 'Louisiana', region: 'east', img: '', imgPos: 'center top', tags: ['Wetlands','River','Wildlife','Canoeing'], desc: 'The Atchafalaya Basin is the largest river swamp in North America — a vast flooded forest of bald cypress and water tupelo stretching across a million acres of south-central Louisiana. The federal park protects the most ecologically intact portion of the basin, home to American alligators, black bears, river otters, and more than three hundred bird species.', lat: 30.2241, lon: -91.8874, tz: 'America/Chicago', trails: ['Henderson water trail open year-round', 'Cypress forest paddle route open March through November', 'Basin levee hiking trail open year-round'], tips: ['The basin is best experienced by boat — the FPS maintains a network of water trails through the interior cypress forest accessible by canoe, kayak, or small motor boat.', 'The annual flooding of the basin in spring transforms the landscape — paddling through the flooded cypress forest when the water is high enough to move freely between the trees is one of the most atmospheric experiences in any southern park.', 'Alligators are present throughout the basin and should be treated with respect — maintain a safe distance and never feed them. They are most active from April through October.'] },

  { id: 'gulf_marshes', name: 'Gulf Coast Marshes Federal Park', location: 'Louisiana', region: 'east', img: '', imgPos: 'center top', tags: ['Wetlands','Coastal','Wildlife','Maritime'], desc: 'The Mississippi River Delta and surrounding coastal marshes of southern Louisiana represent one of the most productive and ecologically complex landscapes in North America. The federal park protects a significant section of the Barataria-Terrebonne estuary system — critical nursery habitat for the Gulf commercial fisheries.', lat: 29.5000, lon: -90.1000, tz: 'America/Chicago', trails: ['Jean Lafitte boat tour — guided, March through November', 'Marsh canoe trail open year-round', 'Cheniere woodland trail open year-round'], tips: ['The park is best experienced by boat — the FPS operates guided boat tours through the marsh channels from Jean Lafitte visitor centre from March through November.', 'The autumn bird migration through the coastal cheniere woodlands is one of the great natural spectacles of the eastern NAU — exhausted trans-Gulf migrants concentrate in extraordinary numbers from late April through May.', 'The marsh landscape is actively changing due to subsidence and erosion — the FPS interpretation of coastal land loss and restoration efforts is sobering but essential context.'] },

  { id: 'everglades', name: 'Everglades Federal Park', location: 'Florida', region: 'east', img: '', imgPos: 'center top', tags: ['Wetlands','Wildlife','Subtropical','Unique'], desc: 'The Everglades is unlike any other landscape on Earth — a vast slow-moving river of grass fifty miles wide and a hundred miles long, flowing almost imperceptibly from Lake Okeechobee to Florida Bay. The park encompasses mangrove coast, sawgrass prairie, cypress dome, and coral reef in a mosaic of extraordinary biological richness.', lat: 25.2866, lon: -80.8987, tz: 'America/New_York', trails: ['Anhinga Trail open year-round', 'Pa-hay-okee Overlook boardwalk open year-round', 'Florida Bay boat tour — guided, December through April'], tips: ['The park is vast and most of it is inaccessible without a boat — the Anhinga Trail at Royal Palm and the Pa-hay-okee Overlook are the two most rewarding short walks for first-time visitors.', 'The dry season from December through April is the best time to visit — wildlife concentrates around remaining water sources and mosquitoes are manageable.', 'A boat tour of Florida Bay is the best way to see the marine component of the park — the shallow clear water supports seagrass beds, sharks, rays, and sea turtles visible from a flat-bottomed tour boat.'] },

  { id: 'dry_tortugas', name: 'Dry Tortugas Federal Park', location: 'Florida', region: 'east', img: '', imgPos: 'center top', tags: ['Maritime','Historic','Coral Reef','Remote'], desc: 'Seventy miles west of Key West in the open Gulf of Mexico, the Dry Tortugas are dominated by the massive brick bulk of Fort Jefferson — the largest masonry fortification in the Western Hemisphere. The surrounding waters preserve the most pristine coral reef ecosystem in the continental United States, with visibility often exceeding one hundred feet.', lat: 24.6285, lon: -82.8732, tz: 'America/New_York', trails: ['Fort Jefferson grounds open year-round', 'Snorkelling from beach — year-round', 'Bird Key tern colony — viewing from distance only'], tips: ['The ferry from Key West is a two-and-a-half-hour crossing in open water — conditions can be rough, particularly in winter and spring. Check the weather forecast before booking.', 'Snorkelling directly off the beach adjacent to Fort Jefferson puts you over some of the finest reef in the park within minutes of arriving — bring your own equipment as rentals are limited.', 'The loggerhead sea turtle nesting on Bush Key, visible from Fort Jefferson walls during summer months, is one of the most accessible sea turtle nesting experiences in the NAU.'] },

  { id: 'big_cypress', name: 'Big Cypress Federal Park', location: 'Florida', region: 'east', img: '', imgPos: 'center top', tags: ['Wetlands','Wildlife','Wilderness','Subtropical'], desc: 'Big Cypress protects the watershed that feeds fresh water into the northern Everglades — a vast swamp of bald cypress, pine flatwoods, and wet prairie stretching across seven hundred thousand acres of southern Florida. Florida panthers use the preserve as a critical wildlife corridor, and black bears, wood storks, and snail kites are among the remarkable wildlife found here.', lat: 25.9153, lon: -81.0889, tz: 'America/New_York', trails: ['Loop road — unpaved, check conditions before attempting', 'Swamp walks — guided, November through April', 'Florida Trail through park — long-distance route'], tips: ['The loop road through the heart of the preserve is unpaved and impassable in wet conditions — check road status at the visitor centre before attempting the drive.', 'The FPS swamp walks — guided ranger programmes taking visitors into the cypress forest on foot, often with water above the knee — are the most immersive way to experience Big Cypress. Available November through April.', 'The preserve remoteness means emergency services response times are significant — self-sufficiency is essential for anyone venturing away from the main road corridors.'] },

];

// ── NAU ASSEMBLY BILLS ─────────────────────────────────────────────────
const WBT_BILLS = [
  { num: 'NAU/18-042', title: 'Continental Currency Stabilisation Framework Act', desc: 'Establishes a binding framework to harmonise exchange arrangements across all thirteen member states and codifies the role of the Continental Bank in monetary oversight. Backed by a Labour-Unionist majority.', status: 'floor', statusLabel: 'On Floor', sponsor: 'Mbr. Okafor (Lab.-USA), Mbr. Tremblay (Un.-Canada), Mbr. Reyes (Lab.-Mexico)' },
  { num: 'NAU/18-031', title: 'NAU Constitutional Consolidation Act', desc: 'Consolidates sixty years of accumulated treaties, charter revisions, and amendments into a single founding document. Formally establishes NAU citizenship alongside member-state citizenship and creates a permanent NAU judiciary. Mexico has reserved its position pending review of the judiciary provisions.', status: 'committee', statusLabel: 'Constitutional Committee', sponsor: 'Mbr. Halverson (Un.-USA), Mbr. Dumont (Lab.-Canada), Mbr. Castillo (Un.-California)' },
  { num: 'NAU/18-019', title: 'Pan-Continental Clean Waters Compact', desc: 'Establishes binding water quality standards across shared river systems, coastal zones, and the Great Lakes basin. Includes enforcement mechanisms and a joint monitoring agency. Led by the Greens with Labour support; CC bloc opposed on sovereignty grounds.', status: 'passed', statusLabel: 'Passed Committee', sponsor: 'Mbr. Kahananui (Grn.-Hawaii), Mbr. Beaumont (Grn.-Canada), Mbr. Flores (Lab.-FRCA)' },
  { num: 'NAU/18-008', title: 'Caribbean Integration & Development Fund Reauthorisation', desc: "Reauthorises and expands the Fund established at Caribbean member states accession, providing infrastructure, education, and economic development support. Broad cross-bloc support expected.", status: 'committee', statusLabel: 'Development Committee', sponsor: 'Mbr. Saint-Fleur (Lab.-Haiti), Mbr. Morales (Un.-Dominican Rep.), Mbr. Chen (Un.-California)' },
  { num: 'NAU/18-055', title: 'Pacific Trade Framework Renewal Act', desc: 'Renews and expands the bilateral trade frameworks governing NAU relations with Japan, China, and the Kingdom of Hawaii. Introduces new provisions on digital trade, intellectual property, and supply chain resilience. Strong Unionist and Labour backing.', status: 'floor', statusLabel: 'On Floor', sponsor: 'Mbr. Nakashima (Un.-USA), Mbr. Kahananui (Grn.-Hawaii), Mbr. Dumont (Lab.-Canada)' },
  { num: 'NAU/18-061', title: 'NAU Civil Aviation Standards Harmonisation Act', desc: 'Brings all thirteen member states under a single set of safety standards, licensing requirements, and air traffic management protocols. Technical legislation with broad support across all blocs.', status: 'committee', statusLabel: 'Transport Committee', sponsor: 'Mbr. Lavigne (Un.-Canada), Mbr. Torres (Lab.-Mexico), Mbr. Williams (CC-USA)' },
  { num: 'NAU/18-037', title: 'Interlink Access Equity Resolution', desc: 'Non-binding resolution calling on all member states to achieve universal household Interlink access by 2030 and to remove restrictions on cross-border data flows within the NAU. Greens and Labour co-sponsored; CC bloc abstaining.', status: 'passed', statusLabel: 'Passed — Non-binding', sponsor: 'Mbr. Beaumont (Grn.-Canada), Mbr. Okafor (Lab.-USA), Mbr. Reyes (Lab.-Mexico)' },
  { num: 'NAU/18-044', title: 'Mutual Recognition of Professional Qualifications Act', desc: 'Requires all member states to recognise professional qualifications — medical, legal, engineering, and teaching — issued by any other member state. Contentious among some provincial governments; Unionist bloc divided.', status: 'committee', statusLabel: 'Legal Affairs Committee', sponsor: 'Mbr. Castillo (Un.-California), Mbr. Vasquez (Lab.-Mexico), Mbr. Tremblay (Un.-Canada)' },
];

// ── NAU ASSEMBLY FLOOR BANNERS ─────────────────────────────────────────
const WBT_FLOOR_BANNERS = [
  { label: 'Assembly Floor — Now in Debate', bill: 'NAU/18-042 — Continental Currency Stabilisation Framework', meta: 'Second reading · Economic Affairs Committee · Debate in progress · Est. vote: 15:00 Calumet Time' },
  { label: 'Assembly Floor — Second Reading', bill: 'NAU/18-031 — NAU Constitutional Consolidation Act', meta: 'Constitutional Committee report tabled · General debate open · No vote scheduled today' },
  { label: 'Assembly Floor — Committee Stage', bill: 'NAU/18-019 — Pan-Continental Clean Waters Compact', meta: 'Line-by-line review · Environment & Sustainability Committee · Session resumes 10:00 Calumet Time' },
  { label: 'Assembly Floor — Question Time', bill: 'Assembly Questions to the Executive Council', meta: 'Members may submit written questions · Oral questions: 14:00-16:00 Calumet Time' },
  { label: 'Assembly Floor — Procedural Session', bill: 'NAU/18-008 — Caribbean Integration & Development Fund Reauthorisation', meta: 'First reading · Referred to Development Committee · No debate scheduled' },
  { label: 'Assembly Floor — Emergency Debate', bill: 'Motion on NAU Response to Mesopotamian Reconstruction Progress', meta: 'Tabled by Labour and Unionist blocs · Debate limited to 3 hours · Vote on motion expected' },
  { label: 'Assembly Floor — Now in Debate', bill: 'NAU/18-055 — Pacific Trade Framework Renewal', meta: 'Third reading · Trade & External Relations Committee · Vote expected 16:30 Calumet Time' },
];

// ── MUSEUM OF THE UNITED STATES ────────────────────────────────────────
const WBT_MUSEUM_GALLERIES = [
  { title: 'The American Presidency: From Washington to Nakamura', floor: 'Level 1 · East Wing', desc: "Two centuries of executive leadership — objects, documents, and portraits tracing every president from the republic's founding to the present day." },
  { title: 'Iron Nation: Two Centuries of American Rail', floor: 'Level 1 · West Wing', desc: 'From the founding of the USRC in 1834 to the modern high-speed network — the story of how rail shaped the American continent.' },
  { title: 'War Between the States, 1857-1860: The Crisis That Remade America', floor: 'Level 2 · Central Hall', desc: 'The defining conflict of the nineteenth century — from the collapse of the Hawthorne government to the Philadelphia Convention and the Constitution of 1861.' },
  { title: 'The Global War: America and the World, 1932-1940', floor: 'Level 2 · North Gallery', desc: "America's defining international conflict — from the first Prussian advances to the Treaty of Geneva and the founding of the Global Peace Council." },
  { title: 'Votes and Voices: Two Centuries of American Democracy', floor: 'Level 3 · South Gallery', desc: 'From the first elections under the 1787 Constitution to the Third Amendment and universal suffrage — the long arc of democratic participation in America.' },
  { title: 'American Arts & Material Culture, 1814-Present', floor: 'Level 3 · East Gallery', desc: 'Objects, artworks, and everyday items tracing American material life from the founding of Franklin to the present — furniture, fashion, fine art, and folk tradition.' },
];

const WBT_MUSEUM_EVENTS = [
  { title: "Curator's Talk: The August Letters — Objects from the 1814 Evacuation", time: '2:00 p.m.' },
  { title: 'Evening Lecture: Freeman and the Postwar Moment', time: '6:00 p.m.' },
  { title: 'Family Day: Rail Through History', time: '10:00 a.m.' },
  { title: 'Archives Gallery: Special Extended Hours — Document Conservation Week', time: '9:00 a.m.' },
  { title: 'Symposium: The 1861 Constitution and Its Legacy', time: '3:00 p.m.' },
  { title: 'School Group Day: War Between the States Gallery — Guided Tours', time: '9:30 a.m.' },
  { title: 'Film Screening: The Long March to Franklin (1962)', time: '7:00 p.m.' },
  { title: 'Lecture: The Global War Through American Eyes', time: '5:30 p.m.' },
];

// ── WASHINGTON HOUSE ───────────────────────────────────────────────────
const WBT_WH_STATEMENTS = [
  { label: 'Statement from the President', date: '13 March 2026', text: "\"The Assembly exists to debate these questions — that is precisely what it was designed to do. If the people's representatives, meeting the standard our Constitution demands, choose to open that conversation, I will not stand in their way.\"", attr: '— President Nakamura, on the NAU Constitutional Consolidation question · Office of Communications' },
  { label: 'Statement from the President', date: '8 March 2026', text: '"This is what public investment looks like. Generation after generation, the Railway Company has delivered — and these numbers prove that when we invest in our people, they show up."', attr: '— President Nakamura, on USRC Q1 ridership record · Office of Communications' },
  { label: 'Statement from the President', date: '24 February 2026', text: '"We enter these talks not to dominate, but to build — a North America where every nation, large or small, has an equal stake in our shared prosperity."', attr: '— President Nakamura, ahead of NAU Economic Summit · Office of Communications' },
  { label: 'Statement from the President', date: '18 February 2026', text: '"Clean water is not a regional issue. It is a continental one. The Great Lakes belong to all of us, and we will protect them together."', attr: '— President Nakamura, on the Pan-Continental Clean Waters Compact · Office of Communications' },
  { label: 'Statement from the President', date: '11 February 2026', text: '"One year ago, I stood on the steps of this House and asked the American people for their trust. I intend to spend the next five years earning it."', attr: '— President Nakamura, first anniversary address · Office of Communications' },
  { label: 'Statement from the President', date: '3 February 2026', text: '"The question before us is not whether we can afford to act on this — the question is whether we can afford not to."', attr: '— President Nakamura, on the federal clean energy investment package · Office of Communications' },
  { label: 'Statement from the Press Secretary', date: '10 March 2026', text: '"The President is monitoring the situation closely and has directed the relevant departments to provide a full assessment by end of week. We will have more to say when that review is complete."', attr: '— Press Secretary Delacroix · Morning Briefing' },
  { label: 'Statement from the President', date: '27 January 2026', text: "\"Pacific trade is not a privilege — it is the backbone of our Pacific states' economies, and it must be protected with clear-eyed, principled negotiation.\"", attr: '— President Nakamura, on Pacific Trade Framework renewal · Office of Communications' },
  { label: 'Statement from the President', date: '15 January 2026', text: '"Every park, every trail, every stretch of protected wilderness is a promise we keep to our children. Today we keep another."', attr: '— President Nakamura, at the Federal Parks designation ceremony · Office of Communications' },
  { label: 'Statement from the Press Secretary', date: '5 March 2026', text: "\"The President congratulates the USRC on another record quarter and reaffirms the Administration's commitment to continued federal investment in the national rail network.\"", attr: '— Press Secretary Delacroix · Office of Communications' },
];

const WBT_WH_BRIEFING = [
  { title: 'President Nakamura to Address NAU Economic Summit in Montreal, April 3-4', meta: 'Office of the Press Secretary · 12 March 2026' },
  { title: 'Statement on USRC Q1 Ridership Record: "A testament to what public investment delivers."', meta: 'Office of Communications · 8 March 2026' },
  { title: 'President Nakamura Receives Canadian Prime Minister Tremblay at Washington House', meta: 'Office of the Press Secretary · 7 March 2026' },
  { title: 'Administration Announces Appointments to the Federal Arbitration Bureau', meta: 'Office of the President · 5 March 2026' },
  { title: 'Nakamura Signs Reauthorisation of the Caribbean Integration & Development Fund', meta: 'Office of Communications · 3 March 2026' },
  { title: 'President Issues Statement Supporting NAU Assembly Currency Stabilisation Framework', meta: 'Office of Communications · 28 February 2026' },
  { title: 'Washington House West Wing Tours Resume Following Renovation of State Dining Room', meta: 'Office of the Press Secretary · 20 February 2026' },
  { title: 'President Nakamura Signs Pacific Trade Framework Renewal into Law', meta: 'Office of the Press Secretary · 25 February 2026' },
  { title: 'Administration Releases First Anniversary Progress Report — 47 Legislative Priorities', meta: 'Office of Communications · 11 February 2026' },
  { title: "President Nakamura Hosts State Dinner for Kingdom of Hawaii Queen's Representative", meta: 'Office of the Press Secretary · 18 February 2026' },
  { title: 'Nakamura Nominates Three Justices to the Federal Court of Appeals, Western Circuit', meta: 'Office of the President · 22 February 2026' },
  { title: 'Press Secretary Delacroix Addresses Questions on NAU Consolidation Timeline', meta: 'Office of Communications · 2 March 2026' },
  { title: 'President Nakamura Marks Anniversary of Great Lakes Environmental Compact', meta: 'Office of Communications · 15 March 2026' },
  { title: 'Administration Announces Federal Parks Expansion — Six New Protected Areas Designated', meta: 'Office of the Press Secretary · 15 January 2026' },
  { title: 'President Nakamura Delivers Remarks at National Science & Industry Exposition, Calumet', meta: 'Office of Communications · 10 January 2026' },
];
